// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MeResponsePreferredLocale.
const (
	MeResponsePreferredLocaleEn MeResponsePreferredLocale = "en"
	MeResponsePreferredLocaleRu MeResponsePreferredLocale = "ru"
)

// Defines values for UserPreferredLocale.
const (
	UserPreferredLocaleEn UserPreferredLocale = "en"
	UserPreferredLocaleRu UserPreferredLocale = "ru"
)

// AccountDeletionInfo defines model for AccountDeletionInfo.
type AccountDeletionInfo struct {
	CanRestoreUntil     time.Time `json:"canRestoreUntil"`
	RequestedAt         time.Time `json:"requestedAt"`
	ScheduledDeletionAt time.Time `json:"scheduledDeletionAt"`
}

// CodeErrorResponse Machine-routable error envelope; emitted by writeJSONCodeError.
// Frontend resolves `code` to a localized message via i18n catalog.
type CodeErrorResponse struct {
	Code string `json:"code"`
}

// ErrorResponse Plain-text error envelope; emitted by writeJSONError.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"accessToken"`
	User        User   `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	AccountDeletion           *AccountDeletionInfo      `json:"accountDeletion"`
	CreatedAt                 time.Time                 `json:"createdAt"`
	Email                     openapi_types.Email       `json:"email"`
	EmailVerificationDeadline *time.Time                `json:"emailVerificationDeadline"`
	EmailVerified             bool                      `json:"emailVerified"`
	Id                        openapi_types.UUID        `json:"id"`
	PreferredLocale           MeResponsePreferredLocale `json:"preferred_locale"`
	RequiresReconsent         *RequiresReconsentInfo    `json:"requiresReconsent"`
	UpdatedAt                 time.Time                 `json:"updatedAt"`
}

// MeResponsePreferredLocale defines model for MeResponse.PreferredLocale.
type MeResponsePreferredLocale string

// RefreshTokenResponse defines model for RefreshTokenResponse.
type RefreshTokenResponse struct {
	AccessToken string `json:"accessToken"`
	User        User   `json:"user"`
}

// RequiresReconsentInfo defines model for RequiresReconsentInfo.
type RequiresReconsentInfo struct {
	Policies []struct {
		AcceptedVersion *string `json:"acceptedVersion"`
		CurrentVersion  string  `json:"currentVersion"`
		Slug            string  `json:"slug"`
	} `json:"policies"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	Email           openapi_types.Email `json:"email"`
	Id              openapi_types.UUID  `json:"id"`
	PreferredLocale UserPreferredLocale `json:"preferred_locale"`
	UpdatedAt       time.Time           `json:"updatedAt"`
}

// UserPreferredLocale defines model for User.PreferredLocale.
type UserPreferredLocale string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xY/24buRF+lQFboDYqyc7FBQ7yX+mdk7qIz4HzAwVOQUyRIy3P3OGWP+SogYE+RJ+w",
	"T1IMuZIl7cZygFzS/6TVcHY488033+iTUK5uHCHFIMafRFAV1jJ/fKaUSxR/RovRODqnmePHlKyVU4ti",
	"HH3CgWi8a9BHg/mQknSFITqPbykay49mztcyirHQMuIwmhrFQMRlg2IsQvSG5uJuIDz+M2GIqJ/Fxx/i",
	"aHWyqFdBPv5w+0rjUYvxr1uv7/c76Nzt/dqpm/6GKnJEPzmNZ947f4WhcRSQ49EYlDcNOxJjcSFVZQiH",
	"3qXIiQRke0BaoHUNngLWJkbUMF3CrTcR//768pe139GEnntHEUmDx+DsAgNcK6fxGqIDCdYpac2/UEON",
	"Icg5wsJIME9+JFAySuvmowmJTt2czqE+nKVs1XftPVd+ZaWhYcSP8VGXLRftxJiP7g+ymPVF+dLNDV2V",
	"SrOfHfe13AFsedKDu0aGcOu8Zuva0EukeazE+Md9KFs5XJ9/IMr7XG6HKZXCEN64G6SeXAxECpiT9EeP",
	"MzEWfzi6b/CjtruP3rLNbnD54GDLf194F7gZm7T2cibGvz7mfYOeq2wyzL6o+wjpblCS+g69mRkl+Yef",
	"UWprCD9LBbsU1snhhkvUG1meOmdRkrjPXLhCxbmguC/6q90DJf4+hKzf3M3/+8FOaz23MkYk1MD1g0Yu",
	"rZMaGpsCLDaSAlNJhH4Auk0fzL1UOABJekJ+FRTMDFodIDg4kilWRzWCR9LoAxgCCcHQ3CJ4l0gPozfN",
	"CN5UCFzhCbWHpUeo0c9Rg6HoIFbspIAGyk3gQJKjZe1SAKynqLWhOThi2wm9cBCMxsPTfHS24rvoUcYA",
	"sTIBZABJgB/5B9T5/cxrdwNxhTOPocoI/v9to3447J2vjbNGtZ9NxDr036yJqN+hD21X7QW8St4jxY0j",
	"3Vlr03w/+Warjr++BLQPpPdy2XGzvmbfybdtaXYmGIPjy+TDFzC+0Vt2KRndOxg8ztB71B/yGM64Q0p1",
	"lhhJDMQWGjbQ1ugvC34nXzma9XTZDWKwkZzNd3WTy35NC8RtnnndoBrOjA8RXl3+BMoxudAcToBpAimu",
	"eAZJN85QDIUYZslaePbqHELyM6lwQiaAdirVSDz3E3MLBPQLozAcycYcPXtx9sub16NaMzexbX481BjM",
	"nEa1Ps0MwGxjEUzIHKEcRS9VhOCSVzh0s2H0KVYwcz4bhDQNGCFWMkIlA0wRaUK1mXtOBkunORK2X5YN",
	"htGEJnS2pVZAmwXTWmC1srrneEIAQ3juEYdcuZXsCkzI8GlS9MhEjCdiko6Pn6pSwvwZJ+IODrbE0+Go",
	"+OuoxJk0Nvl7t6zFNrzmr/c+Ozr0kN0C/Pff/7nn0ywK+QUYWupdKclM5EUnRhMZx+KS8J0zCnMx2Q3X",
	"HQ4YDCW3h2IgFisCEcejJ6PjYeMUw9s1SLIxYiyejo5HT7MCilVu2zJlLGuewm9FmnFnZzydazEukkis",
	"l4S/Or0sopXvke1l09gWgUe/hUJhhab3kfiWKLzbbixmy/yg5DAH/MPx8dd+dzuj8su3uy4bQEhKIWrU",
	"p+DLcIPIgwUY0TLA32JsLskuQTl3Y3DEKT/5wjAd4SOE3LbOZ0X3kHV3Gbp733PJC2m5cXgJcHo5gIW0",
	"RhcyaUE/AOfhWskmqkp+WNXnGm4rbmLGrXXqxqUItdHa4i0rEI21JFYj8LqWPv5UTreZm6YI5AjhVoYJ",
	"hcS5QZ1Xpet/DFvbYR7f162uODl+8tUKv5OVbk7OKWcBlEfN5CptGMHL9pJZBqNn7jOkPBYqbcv+9KsF",
	"2VO+bqBbud0SnFw71HCwrpspd7o+LJH+8I0jbdeHDJWycH4GOAfX7WLyoZheMyefrfZUnDmPRYNWkrRF",
	"Dz5RON0cahV6zJOHY7XI+jyEDCMWUqmupV+KsTj7qCpJc4Q8ueHPsNoL81lJUERkC1mZN/7S/qtGH4go",
	"54EVANOoeM/+14zqUnyQUvn3DrmddEd/Mb1nIThwHsi1QXAHQeMxbw88F4zGunFc1LbQ37Jvrrb4kUNb",
	"9za3fO6Y0lmcYetR6iV4XLibtoH+8hXp/VGwXGW3KKAV4412oNLygYzYblOb15zyMgbrRSuPskdApM7y",
	"dI496HiB8QLF7zj5Nv5F6GvVe0m5s9h+e0RdmBDybuoBPzY8d7basg3o5NsFxOsPeHcL5CLMcukPcDQf",
	"QSW9Hub1HvXh9wHzOc8lkhasczep+RyarzAmXwSn7JT6T0wnLov7QnmrvyZClPFBQLdd8XnS2/xr4PdE",
	"d+9fEH1s5WKZlRsKj/B2h+ZZ5n1X3K8oc3f6fFeEtdACnfIe6ttUdqDGz/tIs80tQ6w2FEHmzG+3dhdq",
	"7Bs9rzlZKydvxVjkrXXxhNXt/wIAAP//nk4X3lAZAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
