// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
	MtlsScopes       = "mtls.Scopes"
)

// Defines values for AuditAction.
const (
	AuthLoginFailed         AuditAction = "auth.login_failed"
	AuthLoginSuccess        AuditAction = "auth.login_success"
	AuthLogout              AuditAction = "auth.logout"
	AuthPasswordChanged     AuditAction = "auth.password_changed"
	AuthUserRegistered      AuditAction = "auth.user_registered"
	BusinessCreated         AuditAction = "business.created"
	BusinessUpdated         AuditAction = "business.updated"
	IntegrationConnected    AuditAction = "integration.connected"
	IntegrationDisconnected AuditAction = "integration.disconnected"
	IntegrationTokenRotated AuditAction = "integration.token_rotated"
	ProjectCreated          AuditAction = "project.created"
	ProjectDeleted          AuditAction = "project.deleted"
	ProjectUpdated          AuditAction = "project.updated"
	RbacInvitationAccepted  AuditAction = "rbac.invitation_accepted"
	RbacInvitationCreated   AuditAction = "rbac.invitation_created"
	RbacInvitationRevoked   AuditAction = "rbac.invitation_revoked"
	RbacMemberRemoved       AuditAction = "rbac.member_removed"
	RbacRoleCreated         AuditAction = "rbac.role_created"
	RbacRoleDeleted         AuditAction = "rbac.role_deleted"
	RbacRoleGranted         AuditAction = "rbac.role_granted"
	RbacRoleUpdated         AuditAction = "rbac.role_updated"
)

// Defines values for AuditEventActionCategory.
const (
	AuditEventActionCategoryAuth        AuditEventActionCategory = "auth"
	AuditEventActionCategoryBusiness    AuditEventActionCategory = "business"
	AuditEventActionCategoryIntegration AuditEventActionCategory = "integration"
	AuditEventActionCategoryOther       AuditEventActionCategory = "other"
	AuditEventActionCategoryProject     AuditEventActionCategory = "project"
	AuditEventActionCategoryRbac        AuditEventActionCategory = "rbac"
)

// Defines values for ChatHistoryEntryRole.
const (
	ChatHistoryEntryRoleAssistant ChatHistoryEntryRole = "assistant"
	ChatHistoryEntryRoleSystem    ChatHistoryEntryRole = "system"
	ChatHistoryEntryRoleTool      ChatHistoryEntryRole = "tool"
	ChatHistoryEntryRoleUser      ChatHistoryEntryRole = "user"
)

// Defines values for ChatRequestProjectWhitelistMode.
const (
	ChatRequestProjectWhitelistModeAll      ChatRequestProjectWhitelistMode = "all"
	ChatRequestProjectWhitelistModeEmpty    ChatRequestProjectWhitelistMode = ""
	ChatRequestProjectWhitelistModeExplicit ChatRequestProjectWhitelistMode = "explicit"
	ChatRequestProjectWhitelistModeInherit  ChatRequestProjectWhitelistMode = "inherit"
	ChatRequestProjectWhitelistModeNone     ChatRequestProjectWhitelistMode = "none"
)

// Defines values for ConsentRequiredResponseCode.
const (
	ConsentRequired ConsentRequiredResponseCode = "consent_required"
)

// Defines values for ConversationTitleStatus.
const (
	ConversationTitleStatusAuto        ConversationTitleStatus = "auto"
	ConversationTitleStatusAutoPending ConversationTitleStatus = "auto_pending"
	ConversationTitleStatusManual      ConversationTitleStatus = "manual"
)

// Defines values for HITLAlreadyResolvedErrorError.
const (
	BatchAlreadyResolved HITLAlreadyResolvedErrorError = "batch already resolved"
)

// Defines values for HITLAlreadyResolvedErrorReason.
const (
	AlreadyResolved HITLAlreadyResolvedErrorReason = "already_resolved"
)

// Defines values for HITLBatchResolvingErrorError.
const (
	BatchResolving HITLBatchResolvingErrorError = "batch resolving"
)

// Defines values for HITLBatchResolvingErrorReason.
const (
	ConcurrentResolveInProgress HITLBatchResolvingErrorReason = "concurrent resolve in progress"
)

// Defines values for HITLDecisionInputAction.
const (
	HITLDecisionInputActionApprove HITLDecisionInputAction = "approve"
	HITLDecisionInputActionEdit    HITLDecisionInputAction = "edit"
	HITLDecisionInputActionReject  HITLDecisionInputAction = "reject"
)

// Defines values for HITLExpiredErrorError.
const (
	ApprovalExpired HITLExpiredErrorError = "approval_expired"
)

// Defines values for HITLRejectReasonTooLongErrorError.
const (
	RejectReasonTooLong HITLRejectReasonTooLongErrorError = "reject_reason too long"
)

// Defines values for HITLResolvedCallAction.
const (
	HITLResolvedCallActionApprove HITLResolvedCallAction = "approve"
	HITLResolvedCallActionEdit    HITLResolvedCallAction = "edit"
	HITLResolvedCallActionReject  HITLResolvedCallAction = "reject"
)

// Defines values for HITLShapeMismatchErrorError.
const (
	ShapeMismatch HITLShapeMismatchErrorError = "shape mismatch"
)

// Defines values for MeResponsePreferredLocale.
const (
	MeResponsePreferredLocaleEn MeResponsePreferredLocale = "en"
	MeResponsePreferredLocaleRu MeResponsePreferredLocale = "ru"
)

// Defines values for MessageRole.
const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleUser      MessageRole = "user"
)

// Defines values for PendingDeletionResponseCode.
const (
	AccountPendingDeletion  PendingDeletionResponseCode = "account_pending_deletion"
	BusinessPendingDeletion PendingDeletionResponseCode = "business_pending_deletion"
)

// Defines values for PlatformStatus.
const (
	Active             PlatformStatus = "active"
	ComingSoon         PlatformStatus = "coming_soon"
	OauthNotConfigured PlatformStatus = "oauth_not_configured"
)

// Defines values for ProjectApprovalOverrides.
const (
	ProjectApprovalOverridesAuto   ProjectApprovalOverrides = "auto"
	ProjectApprovalOverridesManual ProjectApprovalOverrides = "manual"
)

// Defines values for ProjectWhitelistMode.
const (
	ProjectWhitelistModeAll      ProjectWhitelistMode = "all"
	ProjectWhitelistModeExplicit ProjectWhitelistMode = "explicit"
	ProjectWhitelistModeInherit  ProjectWhitelistMode = "inherit"
	ProjectWhitelistModeNone     ProjectWhitelistMode = "none"
)

// Defines values for ProjectRequestApprovalOverrides.
const (
	ProjectRequestApprovalOverridesAuto    ProjectRequestApprovalOverrides = "auto"
	ProjectRequestApprovalOverridesInherit ProjectRequestApprovalOverrides = "inherit"
	ProjectRequestApprovalOverridesManual  ProjectRequestApprovalOverrides = "manual"
)

// Defines values for ProjectRequestWhitelistMode.
const (
	ProjectRequestWhitelistModeAll      ProjectRequestWhitelistMode = "all"
	ProjectRequestWhitelistModeExplicit ProjectRequestWhitelistMode = "explicit"
	ProjectRequestWhitelistModeInherit  ProjectRequestWhitelistMode = "inherit"
	ProjectRequestWhitelistModeNone     ProjectRequestWhitelistMode = "none"
)

// Defines values for RefreshStartedResponseStatus.
const (
	RefreshStarted RefreshStartedResponseStatus = "refresh_started"
)

// Defines values for RefreshTelegramResponseLinkedGroupStatus.
const (
	RefreshTelegramResponseLinkedGroupStatusBotNotMember  RefreshTelegramResponseLinkedGroupStatus = "bot_not_member"
	RefreshTelegramResponseLinkedGroupStatusNoLinkedGroup RefreshTelegramResponseLinkedGroupStatus = "no_linked_group"
	RefreshTelegramResponseLinkedGroupStatusOk            RefreshTelegramResponseLinkedGroupStatus = "ok"
)

// Defines values for ResumeRequestWhitelistMode.
const (
	All      ResumeRequestWhitelistMode = "all"
	Empty    ResumeRequestWhitelistMode = ""
	Explicit ResumeRequestWhitelistMode = "explicit"
	Inherit  ResumeRequestWhitelistMode = "inherit"
	None     ResumeRequestWhitelistMode = "none"
)

// Defines values for ReviewDraftStatus.
const (
	Failed     ReviewDraftStatus = "failed"
	Generating ReviewDraftStatus = "generating"
	Ready      ReviewDraftStatus = "ready"
)

// Defines values for ReviewReplyStatus.
const (
	ReviewReplyStatusError   ReviewReplyStatus = "error"
	ReviewReplyStatusPending ReviewReplyStatus = "pending"
	ReviewReplyStatusReplied ReviewReplyStatus = "replied"
)

// Defines values for SSEConcurrencyErrorCode.
const (
	SseConcurrencyExceeded SSEConcurrencyErrorCode = "sse_concurrency_exceeded"
)

// Defines values for SSEEventApprovalRequiredType.
const (
	ToolApprovalRequired SSEEventApprovalRequiredType = "tool_approval_required"
)

// Defines values for SSEEventDoneType.
const (
	Done SSEEventDoneType = "done"
)

// Defines values for SSEEventErrorType.
const (
	SSEEventErrorTypeError SSEEventErrorType = "error"
)

// Defines values for SSEEventTextType.
const (
	Text SSEEventTextType = "text"
)

// Defines values for SSEEventToolCallType.
const (
	ToolCall SSEEventToolCallType = "tool_call"
)

// Defines values for SSEEventToolRejectedType.
const (
	ToolRejected SSEEventToolRejectedType = "tool_rejected"
)

// Defines values for SSEEventToolResultType.
const (
	ToolResult SSEEventToolResultType = "tool_result"
)

// Defines values for SoleOwnerResponseCode.
const (
	SoleOwnerOfBusinesses SoleOwnerResponseCode = "sole_owner_of_businesses"
)

// Defines values for StatusOkResponseStatus.
const (
	StatusOkResponseStatusOk StatusOkResponseStatus = "ok"
)

// Defines values for TitlerConflictErrorError.
const (
	TitleInFlight     TitlerConflictErrorError = "title_in_flight"
	TitleIsManual     TitlerConflictErrorError = "title_is_manual"
	TitleStateChanged TitlerConflictErrorError = "title_state_changed"
)

// Defines values for TitlerDisabledErrorError.
const (
	TitlerDisabled TitlerDisabledErrorError = "titler_disabled"
)

// Defines values for ToolEntryFloor.
const (
	ToolEntryFloorAuto   ToolEntryFloor = "auto"
	ToolEntryFloorManual ToolEntryFloor = "manual"
)

// Defines values for ToolFloor.
const (
	ToolFloorAuto      ToolFloor = "auto"
	ToolFloorForbidden ToolFloor = "forbidden"
	ToolFloorManual    ToolFloor = "manual"
)

// Defines values for UpdatePreferredLocaleRequestLocale.
const (
	UpdatePreferredLocaleRequestLocaleEn UpdatePreferredLocaleRequestLocale = "en"
	UpdatePreferredLocaleRequestLocaleRu UpdatePreferredLocaleRequestLocale = "ru"
)

// Defines values for UserPreferredLocale.
const (
	En UserPreferredLocale = "en"
	Ru UserPreferredLocale = "ru"
)

// Defines values for VersionMismatchResponseCode.
const (
	VersionMismatch VersionMismatchResponseCode = "version_mismatch"
)

// Defines values for ListAuditLogsParamsCategory.
const (
	ListAuditLogsParamsCategoryAuth        ListAuditLogsParamsCategory = "auth"
	ListAuditLogsParamsCategoryBusiness    ListAuditLogsParamsCategory = "business"
	ListAuditLogsParamsCategoryIntegration ListAuditLogsParamsCategory = "integration"
	ListAuditLogsParamsCategoryProject     ListAuditLogsParamsCategory = "project"
	ListAuditLogsParamsCategoryRbac        ListAuditLogsParamsCategory = "rbac"
)

// Defines values for ListReviewsParamsReplyStatus.
const (
	Error   ListReviewsParamsReplyStatus = "error"
	Pending ListReviewsParamsReplyStatus = "pending"
	Replied ListReviewsParamsReplyStatus = "replied"
)

// AcceptInvitationResponse defines model for AcceptInvitationResponse.
type AcceptInvitationResponse struct {
	BusinessId openapi_types.UUID `json:"business_id" validate:"required,uuid"`
	RoleId     openapi_types.UUID `json:"role_id" validate:"required,uuid"`
}

// AccountDeletionInfo defines model for AccountDeletionInfo.
type AccountDeletionInfo struct {
	CanRestoreUntil     time.Time `json:"canRestoreUntil" validate:"required"`
	RequestedAt         time.Time `json:"requestedAt" validate:"required"`
	ScheduledDeletionAt time.Time `json:"scheduledDeletionAt" validate:"required"`
}

// AgentTask defines model for AgentTask.
type AgentTask struct {
	BusinessId     openapi_types.UUID `json:"businessId" validate:"required,uuid"`
	CompletedAt    *time.Time         `json:"completedAt"`
	CreatedAt      time.Time          `json:"createdAt" validate:"required"`
	DisplayName    *string            `json:"displayName,omitempty"`
	DisplayNameKey *string            `json:"displayNameKey,omitempty"`
	Error          *string            `json:"error,omitempty"`
	ErrorCode      *string            `json:"errorCode,omitempty"`
	Id             string             `json:"id" validate:"required"`

	// Input Free-form per-task input payload.
	Input *interface{} `json:"input,omitempty"`

	// Output Free-form per-task output payload.
	Output    *interface{} `json:"output,omitempty"`
	Platform  string       `json:"platform" validate:"required"`
	StartedAt *time.Time   `json:"startedAt"`
	Status    string       `json:"status" validate:"required"`
	Type      string       `json:"type" validate:"required"`
}

// AgentTaskListResponse defines model for AgentTaskListResponse.
type AgentTaskListResponse struct {
	Tasks []AgentTask `json:"tasks" validate:"required"`
	Total int         `json:"total" validate:"required"`
}

// ApprovalCall defines model for ApprovalCall.
type ApprovalCall struct {
	Args           map[string]interface{} `json:"args" validate:"required"`
	CallId         string                 `json:"call_id" validate:"required"`
	EditableFields []string               `json:"editable_fields" validate:"required"`

	// Floor Per-tool HITL floor (strictness: auto < manual < forbidden).
	// Business-level approvals only persist `auto` / `manual`;
	// `forbidden` is reserved for tool-registry defaults.
	Floor    ToolFloor `json:"floor"`
	ToolName string    `json:"tool_name" validate:"required"`
}

// AuditAction defines model for AuditAction.
type AuditAction string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action           AuditAction              `json:"action"`
	ActionCategory   AuditEventActionCategory `json:"action_category" validate:"required,oneof=rbac auth integration business project other"`
	ActorDisplayName *string                  `json:"actor_display_name"`
	ActorEmail       *openapi_types.Email     `json:"actor_email" validate:"omitempty,email"`
	ActorId          *openapi_types.UUID      `json:"actor_id" validate:"omitempty,uuid"`
	BusinessId       *openapi_types.UUID      `json:"business_id" validate:"omitempty,uuid"`
	CreatedAt        time.Time                `json:"created_at" validate:"required"`
	Details          map[string]interface{}   `json:"details" validate:"required"`
	Id               openapi_types.UUID       `json:"id" validate:"required,uuid"`
	Resource         string                   `json:"resource" validate:"required"`
}

// AuditEventActionCategory defines model for AuditEvent.ActionCategory.
type AuditEventActionCategory string

// AuditLogListResponse defines model for AuditLogListResponse.
type AuditLogListResponse struct {
	Items      []AuditEvent `json:"items" validate:"required"`
	NextCursor *string      `json:"next_cursor"`
}

// AuthURLResponse defines model for AuthURLResponse.
type AuthURLResponse struct {
	Url string `json:"url" validate:"required"`
}

// BillingErrorResponse Error envelope used by the internal billing endpoints. `error`
// values map to pkg/billingclient sentinels.
type BillingErrorResponse struct {
	Detail *string `json:"detail,omitempty"`
	Error  string  `json:"error" validate:"required"`
}

// Business defines model for Business.
type Business struct {
	Address     *string                `json:"address,omitempty"`
	Category    *string                `json:"category,omitempty"`
	CreatedAt   time.Time              `json:"createdAt" validate:"required"`
	Description *string                `json:"description,omitempty"`
	Id          openapi_types.UUID     `json:"id" validate:"required,uuid"`
	LogoUrl     *string                `json:"logoUrl,omitempty"`
	Name        string                 `json:"name" validate:"required"`
	Phone       *string                `json:"phone,omitempty"`
	Settings    map[string]interface{} `json:"settings" validate:"required"`
	UpdatedAt   time.Time              `json:"updatedAt" validate:"required"`
	Website     *string                `json:"website"`
}

// BusinessMembershipRoleRef defines model for BusinessMembershipRoleRef.
type BusinessMembershipRoleRef struct {
	Id   openapi_types.UUID `json:"id" validate:"required,uuid"`
	Name string             `json:"name" validate:"required"`
}

// BusinessMembershipSummary defines model for BusinessMembershipSummary.
type BusinessMembershipSummary struct {
	Id       openapi_types.UUID        `json:"id" validate:"required,uuid"`
	JoinedAt time.Time                 `json:"joined_at" validate:"required"`
	Name     string                    `json:"name" validate:"required"`
	Role     BusinessMembershipRoleRef `json:"role"`
	Status   string                    `json:"status" validate:"required"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword" validate:"required"`
	NewPassword     string `json:"newPassword" validate:"required,min=8"`
}

// ChatHistoryEntry defines model for ChatHistoryEntry.
type ChatHistoryEntry struct {
	Content string               `json:"content" validate:"required"`
	Role    ChatHistoryEntryRole `json:"role" validate:"required,oneof=system user assistant tool"`
}

// ChatHistoryEntryRole defines model for ChatHistoryEntry.Role.
type ChatHistoryEntryRole string

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	ActiveIntegrations       *[]string                        `json:"active_integrations,omitempty"`
	BusinessAddress          *string                          `json:"business_address,omitempty"`
	BusinessApprovals        *map[string]ToolFloor            `json:"business_approvals,omitempty"`
	BusinessCategory         *string                          `json:"business_category,omitempty"`
	BusinessDescription      *string                          `json:"business_description,omitempty"`
	BusinessId               *openapi_types.UUID              `json:"business_id,omitempty" validate:"omitempty,uuid"`
	BusinessName             *string                          `json:"business_name,omitempty"`
	BusinessPhone            *string                          `json:"business_phone,omitempty"`
	BusinessVoiceTone        *[]string                        `json:"business_voice_tone,omitempty"`
	BusinessWebsite          *string                          `json:"business_website,omitempty"`
	History                  *[]ChatHistoryEntry              `json:"history,omitempty"`
	Locale                   *string                          `json:"locale,omitempty"`
	Message                  string                           `json:"message" validate:"required"`
	MessageId                *string                          `json:"message_id,omitempty"`
	Model                    *string                          `json:"model,omitempty"`
	ProjectAllowedTools      *[]string                        `json:"project_allowed_tools,omitempty"`
	ProjectApprovalOverrides *map[string]ToolFloor            `json:"project_approval_overrides,omitempty"`
	ProjectId                *string                          `json:"project_id,omitempty"`
	ProjectName              *string                          `json:"project_name,omitempty"`
	ProjectSystemPrompt      *string                          `json:"project_system_prompt,omitempty"`
	ProjectWhitelistMode     *ChatRequestProjectWhitelistMode `json:"project_whitelist_mode,omitempty" validate:"omitempty,oneof=inherit all explicit none"`
	Tier                     *string                          `json:"tier,omitempty"`
	UserId                   *string                          `json:"user_id,omitempty"`
}

// ChatRequestProjectWhitelistMode defines model for ChatRequest.ProjectWhitelistMode.
type ChatRequestProjectWhitelistMode string

// ChatTurnRequest defines model for ChatTurnRequest.
type ChatTurnRequest struct {
	// Locale BCP-47 language tag (e.g. "ru", "en") for the LLM response language. Takes precedence over the Accept-Language header, which browsers cannot set on fetch. Empty falls back to Accept-Language.
	Locale  *string `json:"locale,omitempty"`
	Message *string `json:"message,omitempty"`
	Model   *string `json:"model,omitempty"`
}

// ChatView defines model for ChatView.
type ChatView struct {
	Messages         []Message         `json:"messages" validate:"required"`
	PendingApprovals []PendingApproval `json:"pendingApprovals" validate:"required"`
}

// CodeErrorResponse Machine-routable error envelope; emitted by writeJSONCodeError.
// Frontend resolves `code` to a localized message via i18n catalog.
type CodeErrorResponse struct {
	Code string `json:"code" validate:"required"`
}

// ConfirmPasswordResetRequest defines model for ConfirmPasswordResetRequest.
type ConfirmPasswordResetRequest struct {
	NewPassword string `json:"newPassword" validate:"required,min=8"`
	Token       string `json:"token" validate:"required,min=1"`
}

// ConnectTelegramRequest defines model for ConnectTelegramRequest.
type ConnectTelegramRequest struct {
	ChannelId      string  `json:"channel_id" validate:"required"`
	TelegramUserId *string `json:"telegram_user_id,omitempty"`
}

// ConnectVKRequest defines model for ConnectVKRequest.
type ConnectVKRequest struct {
	AccessToken string  `json:"access_token" validate:"required"`
	GroupId     *string `json:"group_id,omitempty"`
}

// ConnectYandexRequest defines model for ConnectYandexRequest.
type ConnectYandexRequest struct {
	BusinessName *string `json:"business_name,omitempty"`
	Cookies      string  `json:"cookies" validate:"required"`
	Permalink    *string `json:"permalink,omitempty"`
}

// ConsentRecord Per-policy consent ledger row returned by GET /users/me/consents.
// `withdrawnAt` is optional (`omitempty`): the field is OMITTED from
// the JSON envelope when the row is active. Frontend treats a missing
// `withdrawnAt` as "consent still in force". `sha256` is also optional
// (early ledger rows may not carry the policy hash).
type ConsentRecord struct {
	AcceptedAt  time.Time  `json:"acceptedAt" validate:"required"`
	Sha256      *string    `json:"sha256,omitempty"`
	Slug        string     `json:"slug" validate:"required"`
	Version     string     `json:"version" validate:"required"`
	WithdrawnAt *time.Time `json:"withdrawnAt,omitempty"`
}

// ConsentRequiredResponse defines model for ConsentRequiredResponse.
type ConsentRequiredResponse struct {
	Code    ConsentRequiredResponseCode `json:"code" validate:"required,oneof=consent_required"`
	Missing []string                    `json:"missing" validate:"required"`
}

// ConsentRequiredResponseCode defines model for ConsentRequiredResponse.Code.
type ConsentRequiredResponseCode string

// Conversation defines model for Conversation.
type Conversation struct {
	BusinessId    openapi_types.UUID      `json:"businessId" validate:"required,uuid"`
	CreatedAt     time.Time               `json:"createdAt" validate:"required"`
	Id            string                  `json:"id" validate:"required"`
	LastMessageAt *time.Time              `json:"lastMessageAt"`
	PinnedAt      *time.Time              `json:"pinnedAt"`
	ProjectId     *string                 `json:"projectId"`
	Title         string                  `json:"title" validate:"required"`
	TitleStatus   ConversationTitleStatus `json:"titleStatus" validate:"required,oneof=auto_pending auto manual"`
	UpdatedAt     time.Time               `json:"updatedAt" validate:"required"`
	UserId        openapi_types.UUID      `json:"userId" validate:"required,uuid"`
}

// ConversationTitleStatus defines model for Conversation.TitleStatus.
type ConversationTitleStatus string

// CreateBusinessRequest defines model for CreateBusinessRequest.
type CreateBusinessRequest struct {
	Address     *string `json:"address,omitempty"`
	Category    *string `json:"category,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name" validate:"required"`
	Phone       *string `json:"phone,omitempty"`
	Website     *string `json:"website"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	ProjectId *string `json:"projectId"`
	Title     string  `json:"title" validate:"required,max=200"`
}

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	ExpiresIn *int               `json:"expires_in,omitempty" validate:"omitempty,min=3600,max=2592000"`
	RoleId    openapi_types.UUID `json:"role_id" validate:"required,uuid"`
}

// CreateInvitationResponse defines model for CreateInvitationResponse.
type CreateInvitationResponse struct {
	CreatedAt time.Time          `json:"created_at" validate:"required"`
	ExpiresAt time.Time          `json:"expires_at" validate:"required"`
	Id        openapi_types.UUID `json:"id" validate:"required,uuid"`
	RoleId    openapi_types.UUID `json:"role_id" validate:"required,uuid"`
	Token     string             `json:"token" validate:"required"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Description *string  `json:"description,omitempty"`
	Name        string   `json:"name" validate:"required,min=1"`
	Permissions []string `json:"permissions" validate:"required"`
}

// DailySpendResponse defines model for DailySpendResponse.
type DailySpendResponse struct {
	DailySpendUsd float64 `json:"daily_spend_usd" validate:"required"`
}

// DeleteAccountRequest defines model for DeleteAccountRequest.
type DeleteAccountRequest struct {
	Password string `json:"password" validate:"required,min=1"`
}

// DraftReplyExample defines model for DraftReplyExample.
type DraftReplyExample struct {
	Rating     *int   `json:"rating,omitempty" validate:"omitempty,min=0,max=5"`
	ReplyText  string `json:"replyText" validate:"required"`
	ReviewText string `json:"reviewText" validate:"required"`
}

// DraftReplyRequest defines model for DraftReplyRequest.
type DraftReplyRequest struct {
	AuthorName          *string              `json:"authorName,omitempty"`
	BusinessCategory    *string              `json:"businessCategory,omitempty"`
	BusinessDescription *string              `json:"businessDescription,omitempty"`
	BusinessId          string               `json:"businessId" validate:"required"`
	BusinessName        *string              `json:"businessName,omitempty"`
	Examples            *[]DraftReplyExample `json:"examples,omitempty"`
	Platform            string               `json:"platform" validate:"required"`
	Rating              int                  `json:"rating" validate:"required,min=0,max=5"`
	ReviewText          string               `json:"reviewText" validate:"required"`
}

// DraftReplyResponse defines model for DraftReplyResponse.
type DraftReplyResponse struct {
	DraftReply string  `json:"draftReply" validate:"required"`
	Model      *string `json:"model,omitempty"`
	Provider   *string `json:"provider,omitempty"`
}

// EmailBeforeVerifyRequest defines model for EmailBeforeVerifyRequest.
type EmailBeforeVerifyRequest struct {
	NewEmail openapi_types.Email `json:"newEmail" validate:"required,email"`
}

// ErrorResponse Plain-text error envelope; emitted by writeJSONError.
type ErrorResponse struct {
	Error string `json:"error" validate:"required"`
}

// GoogleLocationRef defines model for GoogleLocationRef.
type GoogleLocationRef struct {
	AccountName  string `json:"account_name" validate:"required"`
	LocationName string `json:"location_name" validate:"required"`
	Title        string `json:"title" validate:"required"`
}

// GoogleLocationsResponse defines model for GoogleLocationsResponse.
type GoogleLocationsResponse struct {
	Locations []GoogleLocationRef `json:"locations" validate:"required"`
}

// GoogleSelectLocationRequest defines model for GoogleSelectLocationRequest.
type GoogleSelectLocationRequest struct {
	AccountId  string `json:"account_id" validate:"required"`
	LocationId string `json:"location_id" validate:"required"`
}

// HITLAlreadyResolvedError defines model for HITLAlreadyResolvedError.
type HITLAlreadyResolvedError struct {
	Error  HITLAlreadyResolvedErrorError  `json:"error" validate:"required"`
	Reason HITLAlreadyResolvedErrorReason `json:"reason" validate:"required,oneof=already_resolved"`
}

// HITLAlreadyResolvedErrorError defines model for HITLAlreadyResolvedError.Error.
type HITLAlreadyResolvedErrorError string

// HITLAlreadyResolvedErrorReason defines model for HITLAlreadyResolvedError.Reason.
type HITLAlreadyResolvedErrorReason string

// HITLBatchResolvingError defines model for HITLBatchResolvingError.
type HITLBatchResolvingError struct {
	Error        HITLBatchResolvingErrorError  `json:"error" validate:"required"`
	Reason       HITLBatchResolvingErrorReason `json:"reason" validate:"required"`
	RetryAfterMs int                           `json:"retry_after_ms" validate:"required"`
}

// HITLBatchResolvingErrorError defines model for HITLBatchResolvingError.Error.
type HITLBatchResolvingErrorError string

// HITLBatchResolvingErrorReason defines model for HITLBatchResolvingError.Reason.
type HITLBatchResolvingErrorReason string

// HITLDecisionInput defines model for HITLDecisionInput.
type HITLDecisionInput struct {
	Action       HITLDecisionInputAction `json:"action" validate:"required,oneof=approve edit reject"`
	EditedArgs   *map[string]interface{} `json:"edited_args,omitempty"`
	Id           string                  `json:"id" validate:"required"`
	RejectReason *string                 `json:"reject_reason,omitempty"`
}

// HITLDecisionInputAction defines model for HITLDecisionInput.Action.
type HITLDecisionInputAction string

// HITLExpiredError defines model for HITLExpiredError.
type HITLExpiredError struct {
	Error HITLExpiredErrorError `json:"error" validate:"required,oneof=approval_expired"`
}

// HITLExpiredErrorError defines model for HITLExpiredError.Error.
type HITLExpiredErrorError string

// HITLFieldNotEditableError defines model for HITLFieldNotEditableError.
type HITLFieldNotEditableError struct {
	Editable []string `json:"editable" validate:"required"`
	Error    string   `json:"error" validate:"required"`
}

// HITLNonScalarFieldError defines model for HITLNonScalarFieldError.
type HITLNonScalarFieldError struct {
	Error string `json:"error" validate:"required"`
	Tool  string `json:"tool" validate:"required"`
}

// HITLRejectReasonTooLongError defines model for HITLRejectReasonTooLongError.
type HITLRejectReasonTooLongError struct {
	Error HITLRejectReasonTooLongErrorError `json:"error" validate:"required"`
	Max   int                               `json:"max" validate:"required"`
}

// HITLRejectReasonTooLongErrorError defines model for HITLRejectReasonTooLongError.Error.
type HITLRejectReasonTooLongErrorError string

// HITLResolveRequest defines model for HITLResolveRequest.
type HITLResolveRequest struct {
	Decisions []HITLDecisionInput `json:"decisions" validate:"required"`
}

// HITLResolveResponse defines model for HITLResolveResponse.
type HITLResolveResponse struct {
	BatchId    string             `json:"batch_id" validate:"required"`
	Decisions  []HITLResolvedCall `json:"decisions" validate:"required"`
	ResolvedAt time.Time          `json:"resolved_at" validate:"required"`
}

// HITLResolvedCall defines model for HITLResolvedCall.
type HITLResolvedCall struct {
	Action HITLResolvedCallAction `json:"action" validate:"required,oneof=approve edit reject"`
	Id     string                 `json:"id" validate:"required"`
	Reason *string                `json:"reason,omitempty"`
}

// HITLResolvedCallAction defines model for HITLResolvedCall.Action.
type HITLResolvedCallAction string

// HITLShapeMismatchError defines model for HITLShapeMismatchError.
type HITLShapeMismatchError struct {
	Error   HITLShapeMismatchErrorError `json:"error" validate:"required"`
	Missing []string                    `json:"missing" validate:"required"`
}

// HITLShapeMismatchErrorError defines model for HITLShapeMismatchError.Error.
type HITLShapeMismatchErrorError string

// Integration defines model for Integration.
type Integration struct {
	BusinessId     openapi_types.UUID     `json:"businessId" validate:"required,uuid"`
	CreatedAt      time.Time              `json:"createdAt" validate:"required"`
	ExternalId     string                 `json:"externalId" validate:"required"`
	Id             openapi_types.UUID     `json:"id" validate:"required,uuid"`
	Metadata       map[string]interface{} `json:"metadata" validate:"required"`
	Platform       string                 `json:"platform" validate:"required"`
	Status         string                 `json:"status" validate:"required"`
	TokenExpiresAt *time.Time             `json:"tokenExpiresAt"`
	UpdatedAt      time.Time              `json:"updatedAt" validate:"required"`
}

// InternalTokenResponse defines model for InternalTokenResponse.
type InternalTokenResponse struct {
	AccessToken        string                  `json:"access_token" validate:"required"`
	ExpiresAt          *time.Time              `json:"expires_at"`
	ExternalId         string                  `json:"external_id" validate:"required"`
	IntegrationId      openapi_types.UUID      `json:"integration_id" validate:"required,uuid"`
	Metadata           *map[string]interface{} `json:"metadata,omitempty"`
	Platform           string                  `json:"platform" validate:"required"`
	UserToken          *string                 `json:"user_token,omitempty"`
	UserTokenExpiresAt *time.Time              `json:"user_token_expires_at"`
}

// InvitationPreview defines model for InvitationPreview.
type InvitationPreview struct {
	BusinessId   openapi_types.UUID `json:"business_id" validate:"required,uuid"`
	BusinessName string             `json:"business_name" validate:"required"`
	ExpiresAt    time.Time          `json:"expires_at" validate:"required"`
	RoleId       openapi_types.UUID `json:"role_id" validate:"required,uuid"`
	RoleName     string             `json:"role_name" validate:"required"`
}

// InvitationStateErrorResponse 410-gone envelope emitted by writeInvitationStateError. `error`
// is always the literal "gone"; `reason` discriminates the cause
// (`expired` / `revoked` / `accepted` / `unknown`) for the
// frontend refusal matrix. `unknown` is the safe default for
// ErrInvitationNotFound — uniform 410 defends against token
// existence enumeration.
type InvitationStateErrorResponse struct {
	Error  string  `json:"error" validate:"required"`
	Reason *string `json:"reason,omitempty"`
}

// ListConsentsResponse defines model for ListConsentsResponse.
type ListConsentsResponse struct {
	Consents []ConsentRecord `json:"consents" validate:"required"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email" validate:"required,email"`
	Password string              `json:"password" validate:"required,min=8"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"accessToken" validate:"required"`
	User        User   `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	AccountDeletion           *AccountDeletionInfo      `json:"accountDeletion,omitempty"`
	CreatedAt                 time.Time                 `json:"createdAt" validate:"required"`
	Email                     openapi_types.Email       `json:"email" validate:"required,email"`
	EmailVerificationDeadline *time.Time                `json:"emailVerificationDeadline,omitempty"`
	EmailVerified             bool                      `json:"emailVerified" validate:"required"`
	Id                        openapi_types.UUID        `json:"id" validate:"required,uuid"`
	Name                      string                    `json:"name" validate:"required"`
	PreferredLocale           MeResponsePreferredLocale `json:"preferred_locale" validate:"required,oneof=ru en"`
	RequiresReconsent         *RequiresReconsentInfo    `json:"requiresReconsent,omitempty"`
	UpdatedAt                 time.Time                 `json:"updatedAt" validate:"required"`
}

// MeResponsePreferredLocale defines model for MeResponse.PreferredLocale.
type MeResponsePreferredLocale string

// Member defines model for Member.
type Member struct {
	InvitedAt *time.Time          `json:"invited_at"`
	InvitedBy *openapi_types.UUID `json:"invited_by" validate:"omitempty,uuid"`
	JoinedAt  time.Time           `json:"joined_at" validate:"required"`
	Role      struct {
		Id          openapi_types.UUID `json:"id" validate:"required,uuid"`
		Name        string             `json:"name" validate:"required"`
		Permissions []string           `json:"permissions" validate:"required"`
	} `json:"role" validate:"required"`
	Status string `json:"status" validate:"required"`
	User   struct {
		Email openapi_types.Email `json:"email" validate:"required,email"`
		Id    openapi_types.UUID  `json:"id" validate:"required,uuid"`
		Name  *string             `json:"name,omitempty"`
	} `json:"user" validate:"required"`
}

// Message defines model for Message.
type Message struct {
	Attachments    *[]MessageAttachment    `json:"attachments,omitempty"`
	Content        string                  `json:"content" validate:"required"`
	ConversationId string                  `json:"conversationId" validate:"required"`
	CreatedAt      time.Time               `json:"createdAt" validate:"required"`
	Id             string                  `json:"id" validate:"required"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Role           MessageRole             `json:"role" validate:"required,oneof=user assistant system"`
	Status         *string                 `json:"status,omitempty"`
	ToolCalls      *[]MessageToolCall      `json:"toolCalls,omitempty"`
	ToolResults    *[]MessageToolResult    `json:"toolResults,omitempty"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageAttachment defines model for MessageAttachment.
type MessageAttachment struct {
	MimeType string `json:"mimeType" validate:"required"`
	Name     string `json:"name" validate:"required"`
	Type     string `json:"type" validate:"required"`
	Url      string `json:"url" validate:"required"`
}

// MessageToolCall defines model for MessageToolCall.
type MessageToolCall struct {
	ApprovalId *string                `json:"approvalId,omitempty"`
	Arguments  map[string]interface{} `json:"arguments" validate:"required"`
	Id         string                 `json:"id" validate:"required"`
	Name       string                 `json:"name" validate:"required"`
	Status     *string                `json:"status,omitempty"`
}

// MessageToolResult defines model for MessageToolResult.
type MessageToolResult struct {
	Code       *string                `json:"code,omitempty"`
	Content    map[string]interface{} `json:"content" validate:"required"`
	IsError    bool                   `json:"isError" validate:"required"`
	ToolCallId string                 `json:"toolCallId" validate:"required"`
}

// MoveConversationRequest defines model for MoveConversationRequest.
type MoveConversationRequest struct {
	ProjectId *string `json:"projectId"`
}

// MyPermissionsResponse defines model for MyPermissionsResponse.
type MyPermissionsResponse struct {
	Permissions []string `json:"permissions" validate:"required"`
}

// PasswordResetErrorResponse Discriminated error envelope emitted by writePasswordResetError.
// `code` is one of `reset_token_invalid` / `reset_token_expired` /
// `password_too_weak`; `message` is a server-localized RU string the
// frontend renders as-is when no i18n catalog entry matches.
type PasswordResetErrorResponse struct {
	Code    string `json:"code" validate:"required"`
	Message string `json:"message" validate:"required"`
}

// PendingApproval defines model for PendingApproval.
type PendingApproval struct {
	BatchId   string                `json:"batchId" validate:"required"`
	Calls     []PendingApprovalCall `json:"calls" validate:"required"`
	CreatedAt time.Time             `json:"createdAt" validate:"required"`
	ExpiresAt time.Time             `json:"expiresAt" validate:"required"`
	MessageId string                `json:"messageId" validate:"required"`
	Status    string                `json:"status" validate:"required"`
}

// PendingApprovalCall defines model for PendingApprovalCall.
type PendingApprovalCall struct {
	Args           map[string]interface{} `json:"args" validate:"required"`
	CallId         string                 `json:"callId" validate:"required"`
	EditableFields []string               `json:"editableFields" validate:"required"`
	ToolName       string                 `json:"toolName" validate:"required"`
}

// PendingDeletionResponse defines model for PendingDeletionResponse.
type PendingDeletionResponse struct {
	Code         PendingDeletionResponseCode `json:"code" validate:"required,oneof=account_pending_deletion business_pending_deletion"`
	DeletionDate string                      `json:"deletionDate" validate:"required"`
	RestoreUrl   string                      `json:"restoreUrl" validate:"required"`
}

// PendingDeletionResponseCode defines model for PendingDeletionResponse.Code.
type PendingDeletionResponseCode string

// PendingInvitation defines model for PendingInvitation.
type PendingInvitation struct {
	CreatedAt time.Time `json:"created_at" validate:"required"`
	CreatedBy struct {
		Email openapi_types.Email `json:"email" validate:"required,email"`
		Id    openapi_types.UUID  `json:"id" validate:"required,uuid"`
	} `json:"created_by" validate:"required"`
	ExpiresAt time.Time          `json:"expires_at" validate:"required"`
	Id        openapi_types.UUID `json:"id" validate:"required,uuid"`
	RoleId    openapi_types.UUID `json:"role_id" validate:"required,uuid"`
	RoleName  string             `json:"role_name" validate:"required"`
}

// Permission defines model for Permission.
type Permission struct {
	Description string `json:"description" validate:"required"`
	Name        string `json:"name" validate:"required"`
}

// PermissionGroup defines model for PermissionGroup.
type PermissionGroup struct {
	Permissions []Permission `json:"permissions" validate:"required"`
	Resource    string       `json:"resource" validate:"required"`
}

// PermissionRegistryResponse defines model for PermissionRegistryResponse.
type PermissionRegistryResponse struct {
	Groups []PermissionGroup `json:"groups" validate:"required"`
}

// Platform defines model for Platform.
type Platform struct {
	Id     string         `json:"id" validate:"required"`
	Status PlatformStatus `json:"status"`
}

// PlatformStatus defines model for PlatformStatus.
type PlatformStatus string

// Post defines model for Post.
type Post struct {
	BusinessId      openapi_types.UUID             `json:"businessId" validate:"required,uuid"`
	Content         string                         `json:"content" validate:"required"`
	CreatedAt       time.Time                      `json:"createdAt" validate:"required"`
	Id              string                         `json:"id" validate:"required"`
	MediaUrls       *[]string                      `json:"mediaUrls,omitempty"`
	PlatformResults *map[string]PostPlatformResult `json:"platformResults,omitempty"`
	PublishedAt     *time.Time                     `json:"publishedAt"`
	ScheduledAt     *time.Time                     `json:"scheduledAt"`
	Status          string                         `json:"status" validate:"required"`
}

// PostListResponse defines model for PostListResponse.
type PostListResponse struct {
	Posts []Post `json:"posts" validate:"required"`
	Total int    `json:"total" validate:"required"`
}

// PostPlatformResult defines model for PostPlatformResult.
type PostPlatformResult struct {
	Error  *string `json:"error,omitempty"`
	PostId string  `json:"postId" validate:"required"`
	Status string  `json:"status" validate:"required"`
	Url    string  `json:"url" validate:"required"`
}

// Project defines model for Project.
type Project struct {
	AllowedTools      []string                             `json:"allowedTools" validate:"required"`
	ApprovalOverrides *map[string]ProjectApprovalOverrides `json:"approvalOverrides,omitempty"`
	BusinessId        openapi_types.UUID                   `json:"businessId" validate:"required,uuid"`
	CreatedAt         time.Time                            `json:"createdAt" validate:"required"`
	Description       *string                              `json:"description,omitempty"`
	Id                openapi_types.UUID                   `json:"id" validate:"required,uuid"`
	Name              string                               `json:"name" validate:"required"`
	QuickActions      []string                             `json:"quickActions" validate:"required"`
	SystemPrompt      *string                              `json:"systemPrompt,omitempty" validate:"omitempty,max=4000"`
	UpdatedAt         time.Time                            `json:"updatedAt" validate:"required"`
	WhitelistMode     ProjectWhitelistMode                 `json:"whitelistMode" validate:"required,oneof=inherit all explicit none"`
}

// ProjectApprovalOverrides defines model for Project.ApprovalOverrides.
type ProjectApprovalOverrides string

// ProjectWhitelistMode defines model for Project.WhitelistMode.
type ProjectWhitelistMode string

// ProjectConversationCountResponse defines model for ProjectConversationCountResponse.
type ProjectConversationCountResponse struct {
	Count int `json:"count" validate:"required"`
}

// ProjectDeleteResponse defines model for ProjectDeleteResponse.
type ProjectDeleteResponse struct {
	DeletedConversations int `json:"deletedConversations" validate:"required"`
	DeletedMessages      int `json:"deletedMessages" validate:"required"`
}

// ProjectRequest defines model for ProjectRequest.
type ProjectRequest struct {
	AllowedTools      *[]string                                   `json:"allowedTools,omitempty"`
	ApprovalOverrides *map[string]ProjectRequestApprovalOverrides `json:"approvalOverrides,omitempty"`
	Description       *string                                     `json:"description,omitempty"`
	Name              string                                      `json:"name" validate:"required"`
	QuickActions      *[]string                                   `json:"quickActions,omitempty"`
	SystemPrompt      *string                                     `json:"systemPrompt,omitempty" validate:"omitempty,max=4000"`
	WhitelistMode     *ProjectRequestWhitelistMode                `json:"whitelistMode,omitempty" validate:"omitempty,oneof=inherit all explicit none"`
}

// ProjectRequestApprovalOverrides defines model for ProjectRequest.ApprovalOverrides.
type ProjectRequestApprovalOverrides string

// ProjectRequestWhitelistMode defines model for ProjectRequest.WhitelistMode.
type ProjectRequestWhitelistMode string

// ReconsentPolicy defines model for ReconsentPolicy.
type ReconsentPolicy struct {
	Sha256  *string `json:"sha256,omitempty"`
	Slug    string  `json:"slug" validate:"required"`
	Version string  `json:"version" validate:"required"`
}

// ReconsentRequest defines model for ReconsentRequest.
type ReconsentRequest struct {
	Policies []ReconsentPolicy `json:"policies" validate:"required"`
}

// RefreshStartedResponse defines model for RefreshStartedResponse.
type RefreshStartedResponse struct {
	Status RefreshStartedResponseStatus `json:"status" validate:"required,oneof=refresh_started"`
}

// RefreshStartedResponseStatus defines model for RefreshStartedResponse.Status.
type RefreshStartedResponseStatus string

// RefreshTelegramRequest defines model for RefreshTelegramRequest.
type RefreshTelegramRequest struct {
	ChannelId string `json:"channel_id" validate:"required"`
}

// RefreshTelegramResponse defines model for RefreshTelegramResponse.
type RefreshTelegramResponse struct {
	ChannelTitle      string                                   `json:"channel_title" validate:"required"`
	LinkedChatId      int64                                    `json:"linked_chat_id" validate:"required"`
	LinkedGroupStatus RefreshTelegramResponseLinkedGroupStatus `json:"linked_group_status" validate:"required,oneof=ok bot_not_member no_linked_group"`
}

// RefreshTelegramResponseLinkedGroupStatus defines model for RefreshTelegramResponse.LinkedGroupStatus.
type RefreshTelegramResponseLinkedGroupStatus string

// RefreshTokenResponse defines model for RefreshTokenResponse.
type RefreshTokenResponse struct {
	AccessToken string `json:"accessToken" validate:"required"`
	User        User   `json:"user"`
}

// RegisterConsents Per-slug version map submitted with /auth/register. The handler enforces
// version-equality (vs `legalconfig.*Version`) and returns 400
// consent_required listing the missing slugs, so individual fields are
// NOT marked `required` at the schema level — a missing field is treated
// as a stale consent, not a schema violation.
type RegisterConsents struct {
	Pdn     *string `json:"pdn,omitempty"`
	Privacy *string `json:"privacy,omitempty"`
	Tos     *string `json:"tos,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Consents Per-slug version map submitted with /auth/register. The handler enforces
	// version-equality (vs `legalconfig.*Version`) and returns 400
	// consent_required listing the missing slugs, so individual fields are
	// NOT marked `required` at the schema level — a missing field is treated
	// as a stale consent, not a schema violation.
	Consents RegisterConsents    `json:"consents"`
	Email    openapi_types.Email `json:"email" validate:"required,email"`
	Name     string              `json:"name" validate:"required,min=2,max=100"`
	Password string              `json:"password" validate:"required,min=8"`
}

// ReplyToReviewRequest defines model for ReplyToReviewRequest.
type ReplyToReviewRequest struct {
	ReplyText string `json:"replyText" validate:"required"`
}

// RequestPasswordResetRequest defines model for RequestPasswordResetRequest.
type RequestPasswordResetRequest struct {
	Email openapi_types.Email `json:"email" validate:"required,email"`
}

// RequiresReconsentInfo defines model for RequiresReconsentInfo.
type RequiresReconsentInfo struct {
	Policies []struct {
		NewVersion string `json:"newVersion" validate:"required"`
		OldVersion string `json:"oldVersion" validate:"required"`
		Sha256     string `json:"sha256" validate:"required"`
		Slug       string `json:"slug" validate:"required"`
	} `json:"policies" validate:"required"`
}

// ResumeRequest defines model for ResumeRequest.
type ResumeRequest struct {
	ActiveIntegrations       *[]string                   `json:"active_integrations,omitempty"`
	AllowedTools             *[]string                   `json:"allowed_tools,omitempty"`
	BusinessApprovals        *map[string]ToolFloor       `json:"business_approvals,omitempty"`
	Model                    *string                     `json:"model,omitempty"`
	ProjectApprovalOverrides *map[string]ToolFloor       `json:"project_approval_overrides,omitempty"`
	Tier                     *string                     `json:"tier,omitempty"`
	WhitelistMode            *ResumeRequestWhitelistMode `json:"whitelist_mode,omitempty" validate:"omitempty,oneof=inherit all explicit none"`
}

// ResumeRequestWhitelistMode defines model for ResumeRequest.WhitelistMode.
type ResumeRequestWhitelistMode string

// Review defines model for Review.
type Review struct {
	AuthorName       string                  `json:"authorName" validate:"required"`
	BusinessId       openapi_types.UUID      `json:"businessId" validate:"required,uuid"`
	CreatedAt        time.Time               `json:"createdAt" validate:"required"`
	DraftError       *string                 `json:"draftError,omitempty"`
	DraftGeneratedAt *time.Time              `json:"draftGeneratedAt,omitempty"`
	DraftReply       *string                 `json:"draftReply,omitempty"`
	DraftStatus      *ReviewDraftStatus      `json:"draftStatus,omitempty" validate:"omitempty,oneof=generating ready failed"`
	ExternalId       string                  `json:"externalId" validate:"required"`
	Id               string                  `json:"id" validate:"required"`
	Platform         string                  `json:"platform" validate:"required"`
	PlatformMeta     *map[string]interface{} `json:"platformMeta,omitempty"`
	Rating           int                     `json:"rating" validate:"required"`
	ReplyStatus      ReviewReplyStatus       `json:"replyStatus" validate:"required,oneof=pending replied error"`
	ReplyText        *string                 `json:"replyText,omitempty"`
	Text             string                  `json:"text" validate:"required"`
}

// ReviewDraftStatus defines model for Review.DraftStatus.
type ReviewDraftStatus string

// ReviewReplyStatus defines model for Review.ReplyStatus.
type ReviewReplyStatus string

// ReviewListResponse defines model for ReviewListResponse.
type ReviewListResponse struct {
	Reviews []Review `json:"reviews" validate:"required"`
	Total   int      `json:"total" validate:"required"`
}

// Role defines model for Role.
type Role struct {
	BusinessId  *openapi_types.UUID `json:"business_id" validate:"omitempty,uuid"`
	Description string              `json:"description" validate:"required"`
	Id          openapi_types.UUID  `json:"id" validate:"required,uuid"`
	IsSystem    bool                `json:"is_system" validate:"required"`
	MemberCount *int                `json:"member_count,omitempty"`
	Name        string              `json:"name" validate:"required"`
	Permissions []string            `json:"permissions" validate:"required"`
}

// SSEConcurrencyError defines model for SSEConcurrencyError.
type SSEConcurrencyError struct {
	Code        SSEConcurrencyErrorCode `json:"code" validate:"required,oneof=sse_concurrency_exceeded"`
	RetryAfterS int                     `json:"retry_after_s" validate:"required"`
}

// SSEConcurrencyErrorCode defines model for SSEConcurrencyError.Code.
type SSEConcurrencyErrorCode string

// SSEEvent Discriminated union over the per-type SSE event schemas. `type`
// is the discriminator. Wire envelope is `data: <json>\n\n`.
type SSEEvent struct {
	union json.RawMessage
}

// SSEEventApprovalRequired defines model for SSEEventApprovalRequired.
type SSEEventApprovalRequired struct {
	BatchId string                       `json:"batch_id" validate:"required"`
	Calls   []ApprovalCall               `json:"calls" validate:"required"`
	Type    SSEEventApprovalRequiredType `json:"type" validate:"required,oneof=tool_approval_required"`
}

// SSEEventApprovalRequiredType defines model for SSEEventApprovalRequired.Type.
type SSEEventApprovalRequiredType string

// SSEEventDone defines model for SSEEventDone.
type SSEEventDone struct {
	Content *string          `json:"content,omitempty"`
	Type    SSEEventDoneType `json:"type" validate:"required,oneof=done"`
}

// SSEEventDoneType defines model for SSEEventDone.Type.
type SSEEventDoneType string

// SSEEventError defines model for SSEEventError.
type SSEEventError struct {
	Code    *string           `json:"code,omitempty"`
	Content *string           `json:"content,omitempty"`
	Type    SSEEventErrorType `json:"type" validate:"required,oneof=error"`
}

// SSEEventErrorType defines model for SSEEventError.Type.
type SSEEventErrorType string

// SSEEventText defines model for SSEEventText.
type SSEEventText struct {
	Content *string          `json:"content,omitempty"`
	Type    SSEEventTextType `json:"type" validate:"required,oneof=text"`
}

// SSEEventTextType defines model for SSEEventText.Type.
type SSEEventTextType string

// SSEEventToolCall defines model for SSEEventToolCall.
type SSEEventToolCall struct {
	ToolArgs           *map[string]interface{} `json:"tool_args,omitempty"`
	ToolCallId         *string                 `json:"tool_call_id,omitempty"`
	ToolDisplayName    *string                 `json:"tool_display_name,omitempty"`
	ToolDisplayNameKey *string                 `json:"tool_display_name_key,omitempty"`
	ToolName           *string                 `json:"tool_name,omitempty"`
	Type               SSEEventToolCallType    `json:"type" validate:"required,oneof=tool_call"`
}

// SSEEventToolCallType defines model for SSEEventToolCall.Type.
type SSEEventToolCallType string

// SSEEventToolRejected defines model for SSEEventToolRejected.
type SSEEventToolRejected struct {
	Error              *string                  `json:"error,omitempty"`
	ToolCallId         *string                  `json:"tool_call_id,omitempty"`
	ToolDisplayName    *string                  `json:"tool_display_name,omitempty"`
	ToolDisplayNameKey *string                  `json:"tool_display_name_key,omitempty"`
	ToolName           *string                  `json:"tool_name,omitempty"`
	Type               SSEEventToolRejectedType `json:"type" validate:"required,oneof=tool_rejected"`
}

// SSEEventToolRejectedType defines model for SSEEventToolRejected.Type.
type SSEEventToolRejectedType string

// SSEEventToolResult defines model for SSEEventToolResult.
type SSEEventToolResult struct {
	Error *string `json:"error,omitempty"`

	// Result Tool reply payload (any JSON).
	Result             *interface{}           `json:"result"`
	ToolCallId         *string                `json:"tool_call_id,omitempty"`
	ToolDisplayName    *string                `json:"tool_display_name,omitempty"`
	ToolDisplayNameKey *string                `json:"tool_display_name_key,omitempty"`
	ToolName           *string                `json:"tool_name,omitempty"`
	Type               SSEEventToolResultType `json:"type" validate:"required,oneof=tool_result"`
}

// SSEEventToolResultType defines model for SSEEventToolResult.Type.
type SSEEventToolResultType string

// SearchResult defines model for SearchResult.
type SearchResult struct {
	ConversationId string     `json:"conversationId" validate:"required"`
	LastMessageAt  *time.Time `json:"lastMessageAt"`
	Marks          *[][]int   `json:"marks,omitempty"`
	MatchCount     int        `json:"matchCount" validate:"required"`
	ProjectId      *string    `json:"projectId"`
	Score          float64    `json:"score" validate:"required"`
	Snippet        *string    `json:"snippet,omitempty"`
	Title          *string    `json:"title,omitempty"`
	TopMessageId   *string    `json:"topMessageId,omitempty"`
}

// SoleOwnerBusinessEntry defines model for SoleOwnerBusinessEntry.
type SoleOwnerBusinessEntry struct {
	Id   openapi_types.UUID `json:"id" validate:"required,uuid"`
	Name string             `json:"name" validate:"required"`
}

// SoleOwnerResponse defines model for SoleOwnerResponse.
type SoleOwnerResponse struct {
	Businesses []SoleOwnerBusinessEntry `json:"businesses" validate:"required"`
	Code       SoleOwnerResponseCode    `json:"code" validate:"required,oneof=sole_owner_of_businesses"`
}

// SoleOwnerResponseCode defines model for SoleOwnerResponse.Code.
type SoleOwnerResponseCode string

// StatusOKResponse `{status:"ok"}` envelope used by ChangePassword. Distinct from
// `StatusOkResponse` (camelCase variant) used by review reply and
// review-refresh handlers.
type StatusOKResponse struct {
	Status string `json:"status" validate:"required"`
}

// StatusOkResponse `{status:"ok"}` envelope used by reviewReply and refreshReviews.
// Enum-pinned variant of `StatusOKResponse`.
type StatusOkResponse struct {
	Status StatusOkResponseStatus `json:"status" validate:"required,oneof=ok"`
}

// StatusOkResponseStatus defines model for StatusOkResponse.Status.
type StatusOkResponseStatus string

// TelegramLoginRequest defines model for TelegramLoginRequest.
type TelegramLoginRequest struct {
	AuthDate             TelegramLoginRequest_AuthDate `json:"auth_date" validate:"required"`
	FirstName            *string                       `json:"first_name,omitempty"`
	Hash                 string                        `json:"hash" validate:"required"`
	Id                   *int64                        `json:"id,omitempty"`
	LastName             *string                       `json:"last_name,omitempty"`
	PhotoUrl             *string                       `json:"photo_url,omitempty"`
	Username             *string                       `json:"username,omitempty"`
	AdditionalProperties map[string]interface{}        `json:"-"`
}

// TelegramLoginRequestAuthDate0 defines model for .
type TelegramLoginRequestAuthDate0 = string

// TelegramLoginRequestAuthDate1 defines model for .
type TelegramLoginRequestAuthDate1 = int

// TelegramLoginRequest_AuthDate defines model for TelegramLoginRequest.AuthDate.
type TelegramLoginRequest_AuthDate struct {
	union json.RawMessage
}

// TelegramLoginVerifiedResponse defines model for TelegramLoginVerifiedResponse.
type TelegramLoginVerifiedResponse struct {
	User     map[string]interface{} `json:"user" validate:"required"`
	Verified bool                   `json:"verified" validate:"required"`
}

// TelemetryEvent defines model for TelemetryEvent.
type TelemetryEvent struct {
	Action        string             `json:"action" validate:"required"`
	CorrelationId *string            `json:"correlationId,omitempty"`
	EventType     string             `json:"eventType" validate:"required"`
	Metadata      *map[string]string `json:"metadata,omitempty"`
	Page          string             `json:"page" validate:"required"`
	Timestamp     string             `json:"timestamp" validate:"required"`
}

// TitlerConflictError defines model for TitlerConflictError.
type TitlerConflictError struct {
	Error   TitlerConflictErrorError `json:"error" validate:"required,oneof=title_is_manual title_in_flight title_state_changed"`
	Message string                   `json:"message" validate:"required"`
}

// TitlerConflictErrorError defines model for TitlerConflictError.Error.
type TitlerConflictErrorError string

// TitlerDisabledError defines model for TitlerDisabledError.
type TitlerDisabledError struct {
	Error   TitlerDisabledErrorError `json:"error" validate:"required,oneof=titler_disabled"`
	Message string                   `json:"message" validate:"required"`
}

// TitlerDisabledErrorError defines model for TitlerDisabledError.Error.
type TitlerDisabledErrorError string

// ToolApprovalsResponse defines model for ToolApprovalsResponse.
type ToolApprovalsResponse struct {
	ToolApprovals map[string]ToolFloor `json:"toolApprovals" validate:"required"`
}

// ToolEntry Locale-resolved tool registry projection returned by the api
// service's hitlGetTools (cached 5 minutes). The `floor` here is the
// wire-effective HITL floor — `auto` or `manual`. Distinct from
// `ToolRegistryEntry` which is the orchestrator's internal-only
// projection that may carry `forbidden`.
type ToolEntry struct {
	Description     string         `json:"description" validate:"required"`
	DisplayName     string         `json:"displayName" validate:"required"`
	DisplayNameKey  *string        `json:"displayNameKey,omitempty"`
	EditableFields  []string       `json:"editableFields" validate:"required"`
	Floor           ToolEntryFloor `json:"floor" validate:"required,oneof=auto manual"`
	Name            string         `json:"name" validate:"required"`
	Platform        string         `json:"platform" validate:"required"`
	UserDescription string         `json:"userDescription" validate:"required"`
}

// ToolEntryFloor defines model for ToolEntry.Floor.
type ToolEntryFloor string

// ToolFloor Per-tool HITL floor (strictness: auto < manual < forbidden).
// Business-level approvals only persist `auto` / `manual`;
// `forbidden` is reserved for tool-registry defaults.
type ToolFloor string

// ToolNamesResponse defines model for ToolNamesResponse.
type ToolNamesResponse struct {
	Names []string `json:"names" validate:"required"`
}

// ToolRegistryEntry Orchestrator's internal tool registry projection. The `floor` may
// carry `forbidden` (in addition to `auto` / `manual`); the api side
// uses `ToolEntry` (auto/manual only).
type ToolRegistryEntry struct {
	Description    string   `json:"description" validate:"required"`
	DisplayName    string   `json:"displayName" validate:"required"`
	DisplayNameKey *string  `json:"displayNameKey,omitempty"`
	EditableFields []string `json:"editableFields" validate:"required"`

	// Floor Per-tool HITL floor (strictness: auto < manual < forbidden).
	// Business-level approvals only persist `auto` / `manual`;
	// `forbidden` is reserved for tool-registry defaults.
	Floor           ToolFloor `json:"floor"`
	Name            string    `json:"name" validate:"required"`
	Platform        string    `json:"platform" validate:"required"`
	UserDescription string    `json:"userDescription" validate:"required"`
}

// UpdateBusinessRequest defines model for UpdateBusinessRequest.
type UpdateBusinessRequest struct {
	Address     *string `json:"address,omitempty"`
	Category    *string `json:"category,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name" validate:"required"`
	Phone       *string `json:"phone,omitempty"`
	Website     *string `json:"website"`
}

// UpdateConversationRequest defines model for UpdateConversationRequest.
type UpdateConversationRequest struct {
	Title string `json:"title" validate:"required,max=200"`
}

// UpdateMemberRoleRequest defines model for UpdateMemberRoleRequest.
type UpdateMemberRoleRequest struct {
	RoleId openapi_types.UUID `json:"role_id" validate:"required,uuid"`
}

// UpdateMemberRoleResponse defines model for UpdateMemberRoleResponse.
type UpdateMemberRoleResponse struct {
	BusinessId    openapi_types.UUID  `json:"business_id" validate:"required,uuid"`
	RoleChangedAt *time.Time          `json:"role_changed_at"`
	RoleChangedBy *openapi_types.UUID `json:"role_changed_by" validate:"omitempty,uuid"`
	RoleId        openapi_types.UUID  `json:"role_id" validate:"required,uuid"`
	Status        string              `json:"status" validate:"required"`
	UserId        openapi_types.UUID  `json:"user_id" validate:"required,uuid"`
}

// UpdatePreferredLocaleRequest defines model for UpdatePreferredLocaleRequest.
type UpdatePreferredLocaleRequest struct {
	Locale UpdatePreferredLocaleRequestLocale `json:"locale" validate:"required,oneof=ru en"`
}

// UpdatePreferredLocaleRequestLocale defines model for UpdatePreferredLocaleRequest.Locale.
type UpdatePreferredLocaleRequestLocale string

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Name string `json:"name" validate:"required,min=2,max=100"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest = CreateRoleRequest

// UpdateScheduleRequest defines model for UpdateScheduleRequest.
type UpdateScheduleRequest struct {
	// Schedule Free-form per-day schedule blob.
	Schedule *interface{} `json:"schedule,omitempty"`

	// SpecialDates Optional special-date overrides.
	SpecialDates *interface{} `json:"specialDates,omitempty"`
}

// UpdateToolApprovalsRequest defines model for UpdateToolApprovalsRequest.
type UpdateToolApprovalsRequest struct {
	ToolApprovals map[string]ToolFloor `json:"toolApprovals" validate:"required"`
}

// UpdateVoiceToneRequest defines model for UpdateVoiceToneRequest.
type UpdateVoiceToneRequest struct {
	Tones *[]string `json:"tones,omitempty"`
}

// UploadLogoRequest defines model for UploadLogoRequest.
type UploadLogoRequest struct {
	Logo openapi_types.File `json:"logo" validate:"required"`
}

// UsageLog defines model for UsageLog.
type UsageLog struct {
	BusinessId          openapi_types.UUID  `json:"business_id" validate:"required,uuid"`
	CacheCreationTokens *int                `json:"cache_creation_tokens,omitempty" validate:"omitempty,min=0"`
	CacheReadTokens     *int                `json:"cache_read_tokens,omitempty" validate:"omitempty,min=0"`
	CommissionUsd       float64             `json:"commission_usd" validate:"required"`
	ConversationId      *string             `json:"conversation_id,omitempty"`
	CreatedAt           *time.Time          `json:"created_at,omitempty"`
	Id                  *openapi_types.UUID `json:"id,omitempty" validate:"omitempty,uuid"`
	InputTokens         int                 `json:"input_tokens" validate:"required,min=0"`
	Model               string              `json:"model" validate:"required"`
	OutputTokens        int                 `json:"output_tokens" validate:"required,min=0"`
	Provider            string              `json:"provider" validate:"required"`
	ProviderCostUsd     float64             `json:"provider_cost_usd" validate:"required"`
	RequestId           *string             `json:"request_id,omitempty"`
	UserCostUsd         float64             `json:"user_cost_usd" validate:"required"`
	UserId              openapi_types.UUID  `json:"user_id" validate:"required,uuid"`
	UserTier            string              `json:"user_tier" validate:"required"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt" validate:"required"`
	Email           openapi_types.Email `json:"email" validate:"required,email"`
	Id              openapi_types.UUID  `json:"id" validate:"required,uuid"`
	Name            string              `json:"name" validate:"required"`
	PreferredLocale UserPreferredLocale `json:"preferred_locale" validate:"required,oneof=ru en"`
	UpdatedAt       time.Time           `json:"updatedAt" validate:"required"`
}

// UserPreferredLocale defines model for User.PreferredLocale.
type UserPreferredLocale string

// VKCommunity defines model for VKCommunity.
type VKCommunity struct {
	Id           int64   `json:"id" validate:"required"`
	MembersCount *int    `json:"members_count,omitempty"`
	Name         string  `json:"name" validate:"required"`
	Photo50      *string `json:"photo_50,omitempty"`
	ScreenName   string  `json:"screen_name" validate:"required"`
}

// ValidationErrorResponse Field-level validation error envelope; emitted by writeValidationError.
// `error` carries a localized summary; `fields` maps field name to
// localized per-field message keyed by validator/v10 tag.
type ValidationErrorResponse struct {
	Error  string            `json:"error" validate:"required"`
	Fields map[string]string `json:"fields" validate:"required"`
}

// VerifyConfirmRequest defines model for VerifyConfirmRequest.
type VerifyConfirmRequest struct {
	Token string `json:"token" validate:"required,min=20"`
}

// VersionMismatchResponse defines model for VersionMismatchResponse.
type VersionMismatchResponse struct {
	Code           VersionMismatchResponseCode `json:"code" validate:"required,oneof=version_mismatch"`
	CurrentVersion string                      `json:"currentVersion" validate:"required"`
}

// VersionMismatchResponseCode defines model for VersionMismatchResponse.Code.
type VersionMismatchResponseCode string

// YandexCompaniesResponse defines model for YandexCompaniesResponse.
type YandexCompaniesResponse struct {
	Companies []YandexCompanyEntry `json:"companies" validate:"required"`
}

// YandexCompanyEntry defines model for YandexCompanyEntry.
type YandexCompanyEntry struct {
	Name      string `json:"name" validate:"required"`
	Permalink string `json:"permalink" validate:"required"`
}

// YandexCookiesRequest defines model for YandexCookiesRequest.
type YandexCookiesRequest struct {
	Cookies string `json:"cookies" validate:"required"`
}

// YandexProbeResponse defines model for YandexProbeResponse.
type YandexProbeResponse struct {
	Error        *string   `json:"error,omitempty"`
	Format       *string   `json:"format,omitempty"`
	Ok           bool      `json:"ok" validate:"required"`
	SessionValid *bool     `json:"session_valid,omitempty"`
	Username     *string   `json:"username,omitempty"`
	Warnings     *[]string `json:"warnings,omitempty"`
}

// BusinessIDPath defines model for BusinessIDPath.
type BusinessIDPath = openapi_types.UUID

// IntegrationIDPath defines model for IntegrationIDPath.
type IntegrationIDPath = openapi_types.UUID

// InvitationTokenPath defines model for InvitationTokenPath.
type InvitationTokenPath = string

// RoleIDPath defines model for RoleIDPath.
type RoleIDPath = openapi_types.UUID

// UserIDPath defines model for UserIDPath.
type UserIDPath = openapi_types.UUID

// BusinessNotFound Plain-text error envelope; emitted by writeJSONError.
type BusinessNotFound = ErrorResponse

// InternalError Machine-routable error envelope; emitted by writeJSONCodeError.
// Frontend resolves `code` to a localized message via i18n catalog.
type InternalError = CodeErrorResponse

// Unauthorized Plain-text error envelope; emitted by writeJSONError.
type Unauthorized = ErrorResponse

// InternalGetDailySpendParams defines parameters for InternalGetDailySpend.
type InternalGetDailySpendParams struct {
	BusinessId openapi_types.UUID `form:"business_id" json:"business_id"`
	Date       string             `form:"date" json:"date"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	Category *ListAuditLogsParamsCategory `form:"category,omitempty" json:"category,omitempty"`
	Action   *AuditAction                 `form:"action,omitempty" json:"action,omitempty"`
	Actor    *openapi_types.UUID          `form:"actor,omitempty" json:"actor,omitempty"`
	From     *time.Time                   `form:"from,omitempty" json:"from,omitempty"`
	To       *time.Time                   `form:"to,omitempty" json:"to,omitempty"`
	Cursor   *string                      `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *int                         `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditLogsParamsCategory defines parameters for ListAuditLogs.
type ListAuditLogsParamsCategory string

// ChatTurnParams defines parameters for ChatTurn.
type ChatTurnParams struct {
	BatchId                *string `form:"batch_id,omitempty" json:"batch_id,omitempty"`
	XOnevoiceResumeBatchId *string `json:"X-Onevoice-Resume-Batch-Id,omitempty"`
}

// HitlResumeParams defines parameters for HitlResume.
type HitlResumeParams struct {
	BatchId string `form:"batch_id" json:"batch_id"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetVKCommunityAuthURLParams defines parameters for GetVKCommunityAuthURL.
type GetVKCommunityAuthURLParams struct {
	// GroupId Numeric VK group_id, screen_name, or full VK URL. Resolved
	// server-side to a numeric id before the OAuth URL is built.
	GroupId string `form:"group_id" json:"group_id"`
}

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	Platform *string `form:"platform,omitempty" json:"platform,omitempty"`
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListReviewsParams defines parameters for ListReviews.
type ListReviewsParams struct {
	Platform    *string                       `form:"platform,omitempty" json:"platform,omitempty"`
	ReplyStatus *ListReviewsParamsReplyStatus `form:"reply_status,omitempty" json:"reply_status,omitempty"`
	Limit       *int                          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *int                          `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListReviewsParamsReplyStatus defines parameters for ListReviews.
type ListReviewsParamsReplyStatus string

// CreateRoleParams defines parameters for CreateRole.
type CreateRoleParams struct {
	// CloneFrom Hint for the frontend pre-fill flow; ignored server-side.
	CloneFrom *openapi_types.UUID `form:"clone_from,omitempty" json:"clone_from,omitempty"`
}

// DeleteRoleParams defines parameters for DeleteRole.
type DeleteRoleParams struct {
	// ReassignTo Destination role for members holding the doomed role.
	ReassignTo *openapi_types.UUID `form:"reassign_to,omitempty" json:"reassign_to,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q         string  `form:"q" json:"q"`
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAgentTasksParams defines parameters for ListAgentTasks.
type ListAgentTasksParams struct {
	Platform *string `form:"platform,omitempty" json:"platform,omitempty"`
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	Type     *string `form:"type,omitempty" json:"type,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// OrchestratorChatParams defines parameters for OrchestratorChat.
type OrchestratorChatParams struct {
	XCorrelationID *string `json:"X-Correlation-ID,omitempty"`
}

// OrchestratorResumeParams defines parameters for OrchestratorResume.
type OrchestratorResumeParams struct {
	BatchId        string  `form:"batch_id" json:"batch_id"`
	XCorrelationID *string `json:"X-Correlation-ID,omitempty"`
}

// GoogleBusinessOAuthCallbackParams defines parameters for GoogleBusinessOAuthCallback.
type GoogleBusinessOAuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// VkOAuthCallbackParams defines parameters for VkOAuthCallback.
type VkOAuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// VkCommunityOAuthCallbackParams defines parameters for VkCommunityOAuthCallback.
type VkCommunityOAuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// YandexBusinessOAuthCallbackParams defines parameters for YandexBusinessOAuthCallback.
type YandexBusinessOAuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// IngestTelemetryJSONBody defines parameters for IngestTelemetry.
type IngestTelemetryJSONBody = []TelemetryEvent

// InternalGetTokenParams defines parameters for InternalGetToken.
type InternalGetTokenParams struct {
	BusinessId openapi_types.UUID `form:"business_id" json:"business_id"`
	Platform   string             `form:"platform" json:"platform"`
	ExternalId *string            `form:"external_id,omitempty" json:"external_id,omitempty"`
}

// ReconsentJSONRequestBody defines body for Reconsent for application/json ContentType.
type ReconsentJSONRequestBody = ReconsentRequest

// ChangeEmailBeforeVerifyJSONRequestBody defines body for ChangeEmailBeforeVerify for application/json ContentType.
type ChangeEmailBeforeVerifyJSONRequestBody = EmailBeforeVerifyRequest

// UpdatePreferredLocaleJSONRequestBody defines body for UpdatePreferredLocale for application/json ContentType.
type UpdatePreferredLocaleJSONRequestBody = UpdatePreferredLocaleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = ConfirmPasswordResetRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = RequestPasswordResetRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ConfirmEmailVerificationJSONRequestBody defines body for ConfirmEmailVerification for application/json ContentType.
type ConfirmEmailVerificationJSONRequestBody = VerifyConfirmRequest

// InternalLogUsageJSONRequestBody defines body for InternalLogUsage for application/json ContentType.
type InternalLogUsageJSONRequestBody = UsageLog

// CreateBusinessJSONRequestBody defines body for CreateBusiness for application/json ContentType.
type CreateBusinessJSONRequestBody = CreateBusinessRequest

// UpdateBusinessJSONRequestBody defines body for UpdateBusiness for application/json ContentType.
type UpdateBusinessJSONRequestBody = UpdateBusinessRequest

// ChatTurnJSONRequestBody defines body for ChatTurn for application/json ContentType.
type ChatTurnJSONRequestBody = ChatTurnRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// UpdateConversationJSONRequestBody defines body for UpdateConversation for application/json ContentType.
type UpdateConversationJSONRequestBody = UpdateConversationRequest

// MoveConversationJSONRequestBody defines body for MoveConversation for application/json ContentType.
type MoveConversationJSONRequestBody = MoveConversationRequest

// HitlResolveBatchJSONRequestBody defines body for HitlResolveBatch for application/json ContentType.
type HitlResolveBatchJSONRequestBody = HITLResolveRequest

// SelectGoogleLocationJSONRequestBody defines body for SelectGoogleLocation for application/json ContentType.
type SelectGoogleLocationJSONRequestBody = GoogleSelectLocationRequest

// ConnectTelegramJSONRequestBody defines body for ConnectTelegram for application/json ContentType.
type ConnectTelegramJSONRequestBody = ConnectTelegramRequest

// RefreshTelegramLinkedGroupJSONRequestBody defines body for RefreshTelegramLinkedGroup for application/json ContentType.
type RefreshTelegramLinkedGroupJSONRequestBody = RefreshTelegramRequest

// VerifyTelegramLoginJSONRequestBody defines body for VerifyTelegramLogin for application/json ContentType.
type VerifyTelegramLoginJSONRequestBody = TelegramLoginRequest

// ConnectVKJSONRequestBody defines body for ConnectVK for application/json ContentType.
type ConnectVKJSONRequestBody = ConnectVKRequest

// ListYandexCompaniesJSONRequestBody defines body for ListYandexCompanies for application/json ContentType.
type ListYandexCompaniesJSONRequestBody = YandexCookiesRequest

// ConnectYandexBusinessJSONRequestBody defines body for ConnectYandexBusiness for application/json ContentType.
type ConnectYandexBusinessJSONRequestBody = ConnectYandexRequest

// ProbeYandexBusinessJSONRequestBody defines body for ProbeYandexBusiness for application/json ContentType.
type ProbeYandexBusinessJSONRequestBody = YandexCookiesRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = CreateInvitationRequest

// UploadBusinessLogoMultipartRequestBody defines body for UploadBusinessLogo for multipart/form-data ContentType.
type UploadBusinessLogoMultipartRequestBody = UploadLogoRequest

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRoleRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectRequest

// ReplyToReviewJSONRequestBody defines body for ReplyToReview for application/json ContentType.
type ReplyToReviewJSONRequestBody = ReplyToReviewRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = UpdateRoleRequest

// UpdateBusinessScheduleJSONRequestBody defines body for UpdateBusinessSchedule for application/json ContentType.
type UpdateBusinessScheduleJSONRequestBody = UpdateScheduleRequest

// UpdateBusinessToolApprovalsJSONRequestBody defines body for UpdateBusinessToolApprovals for application/json ContentType.
type UpdateBusinessToolApprovalsJSONRequestBody = UpdateToolApprovalsRequest

// UpdateBusinessVoiceToneJSONRequestBody defines body for UpdateBusinessVoiceTone for application/json ContentType.
type UpdateBusinessVoiceToneJSONRequestBody = UpdateVoiceToneRequest

// OrchestratorChatJSONRequestBody defines body for OrchestratorChat for application/json ContentType.
type OrchestratorChatJSONRequestBody = ChatRequest

// OrchestratorResumeJSONRequestBody defines body for OrchestratorResume for application/json ContentType.
type OrchestratorResumeJSONRequestBody = ResumeRequest

// OrchestratorDraftReplyJSONRequestBody defines body for OrchestratorDraftReply for application/json ContentType.
type OrchestratorDraftReplyJSONRequestBody = DraftReplyRequest

// IngestTelemetryJSONRequestBody defines body for IngestTelemetry for application/json ContentType.
type IngestTelemetryJSONRequestBody = IngestTelemetryJSONBody

// DeleteAccountJSONRequestBody defines body for DeleteAccount for application/json ContentType.
type DeleteAccountJSONRequestBody = DeleteAccountRequest

// Getter for additional properties for TelegramLoginRequest. Returns the specified
// element and whether it was found
func (a TelegramLoginRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for TelegramLoginRequest
func (a *TelegramLoginRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for TelegramLoginRequest to handle AdditionalProperties
func (a *TelegramLoginRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["auth_date"]; found {
		err = json.Unmarshal(raw, &a.AuthDate)
		if err != nil {
			return fmt.Errorf("error reading 'auth_date': %w", err)
		}
		delete(object, "auth_date")
	}

	if raw, found := object["first_name"]; found {
		err = json.Unmarshal(raw, &a.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'first_name': %w", err)
		}
		delete(object, "first_name")
	}

	if raw, found := object["hash"]; found {
		err = json.Unmarshal(raw, &a.Hash)
		if err != nil {
			return fmt.Errorf("error reading 'hash': %w", err)
		}
		delete(object, "hash")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["last_name"]; found {
		err = json.Unmarshal(raw, &a.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'last_name': %w", err)
		}
		delete(object, "last_name")
	}

	if raw, found := object["photo_url"]; found {
		err = json.Unmarshal(raw, &a.PhotoUrl)
		if err != nil {
			return fmt.Errorf("error reading 'photo_url': %w", err)
		}
		delete(object, "photo_url")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for TelegramLoginRequest to handle AdditionalProperties
func (a TelegramLoginRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["auth_date"], err = json.Marshal(a.AuthDate)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'auth_date': %w", err)
	}

	if a.FirstName != nil {
		object["first_name"], err = json.Marshal(a.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'first_name': %w", err)
		}
	}

	object["hash"], err = json.Marshal(a.Hash)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hash': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.LastName != nil {
		object["last_name"], err = json.Marshal(a.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_name': %w", err)
		}
	}

	if a.PhotoUrl != nil {
		object["photo_url"], err = json.Marshal(a.PhotoUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'photo_url': %w", err)
		}
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsSSEEventText returns the union data inside the SSEEvent as a SSEEventText
func (t SSEEvent) AsSSEEventText() (SSEEventText, error) {
	var body SSEEventText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventText overwrites any union data inside the SSEEvent as the provided SSEEventText
func (t *SSEEvent) FromSSEEventText(v SSEEventText) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventText performs a merge with any union data inside the SSEEvent, using the provided SSEEventText
func (t *SSEEvent) MergeSSEEventText(v SSEEventText) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventToolCall returns the union data inside the SSEEvent as a SSEEventToolCall
func (t SSEEvent) AsSSEEventToolCall() (SSEEventToolCall, error) {
	var body SSEEventToolCall
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventToolCall overwrites any union data inside the SSEEvent as the provided SSEEventToolCall
func (t *SSEEvent) FromSSEEventToolCall(v SSEEventToolCall) error {
	v.Type = "tool_call"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventToolCall performs a merge with any union data inside the SSEEvent, using the provided SSEEventToolCall
func (t *SSEEvent) MergeSSEEventToolCall(v SSEEventToolCall) error {
	v.Type = "tool_call"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventToolResult returns the union data inside the SSEEvent as a SSEEventToolResult
func (t SSEEvent) AsSSEEventToolResult() (SSEEventToolResult, error) {
	var body SSEEventToolResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventToolResult overwrites any union data inside the SSEEvent as the provided SSEEventToolResult
func (t *SSEEvent) FromSSEEventToolResult(v SSEEventToolResult) error {
	v.Type = "tool_result"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventToolResult performs a merge with any union data inside the SSEEvent, using the provided SSEEventToolResult
func (t *SSEEvent) MergeSSEEventToolResult(v SSEEventToolResult) error {
	v.Type = "tool_result"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventToolRejected returns the union data inside the SSEEvent as a SSEEventToolRejected
func (t SSEEvent) AsSSEEventToolRejected() (SSEEventToolRejected, error) {
	var body SSEEventToolRejected
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventToolRejected overwrites any union data inside the SSEEvent as the provided SSEEventToolRejected
func (t *SSEEvent) FromSSEEventToolRejected(v SSEEventToolRejected) error {
	v.Type = "tool_rejected"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventToolRejected performs a merge with any union data inside the SSEEvent, using the provided SSEEventToolRejected
func (t *SSEEvent) MergeSSEEventToolRejected(v SSEEventToolRejected) error {
	v.Type = "tool_rejected"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventApprovalRequired returns the union data inside the SSEEvent as a SSEEventApprovalRequired
func (t SSEEvent) AsSSEEventApprovalRequired() (SSEEventApprovalRequired, error) {
	var body SSEEventApprovalRequired
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventApprovalRequired overwrites any union data inside the SSEEvent as the provided SSEEventApprovalRequired
func (t *SSEEvent) FromSSEEventApprovalRequired(v SSEEventApprovalRequired) error {
	v.Type = "tool_approval_required"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventApprovalRequired performs a merge with any union data inside the SSEEvent, using the provided SSEEventApprovalRequired
func (t *SSEEvent) MergeSSEEventApprovalRequired(v SSEEventApprovalRequired) error {
	v.Type = "tool_approval_required"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventDone returns the union data inside the SSEEvent as a SSEEventDone
func (t SSEEvent) AsSSEEventDone() (SSEEventDone, error) {
	var body SSEEventDone
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventDone overwrites any union data inside the SSEEvent as the provided SSEEventDone
func (t *SSEEvent) FromSSEEventDone(v SSEEventDone) error {
	v.Type = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventDone performs a merge with any union data inside the SSEEvent, using the provided SSEEventDone
func (t *SSEEvent) MergeSSEEventDone(v SSEEventDone) error {
	v.Type = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEEventError returns the union data inside the SSEEvent as a SSEEventError
func (t SSEEvent) AsSSEEventError() (SSEEventError, error) {
	var body SSEEventError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEEventError overwrites any union data inside the SSEEvent as the provided SSEEventError
func (t *SSEEvent) FromSSEEventError(v SSEEventError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEEventError performs a merge with any union data inside the SSEEvent, using the provided SSEEventError
func (t *SSEEvent) MergeSSEEventError(v SSEEventError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SSEEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SSEEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "done":
		return t.AsSSEEventDone()
	case "error":
		return t.AsSSEEventError()
	case "text":
		return t.AsSSEEventText()
	case "tool_approval_required":
		return t.AsSSEEventApprovalRequired()
	case "tool_call":
		return t.AsSSEEventToolCall()
	case "tool_rejected":
		return t.AsSSEEventToolRejected()
	case "tool_result":
		return t.AsSSEEventToolResult()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SSEEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SSEEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTelegramLoginRequestAuthDate0 returns the union data inside the TelegramLoginRequest_AuthDate as a TelegramLoginRequestAuthDate0
func (t TelegramLoginRequest_AuthDate) AsTelegramLoginRequestAuthDate0() (TelegramLoginRequestAuthDate0, error) {
	var body TelegramLoginRequestAuthDate0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramLoginRequestAuthDate0 overwrites any union data inside the TelegramLoginRequest_AuthDate as the provided TelegramLoginRequestAuthDate0
func (t *TelegramLoginRequest_AuthDate) FromTelegramLoginRequestAuthDate0(v TelegramLoginRequestAuthDate0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTelegramLoginRequestAuthDate0 performs a merge with any union data inside the TelegramLoginRequest_AuthDate, using the provided TelegramLoginRequestAuthDate0
func (t *TelegramLoginRequest_AuthDate) MergeTelegramLoginRequestAuthDate0(v TelegramLoginRequestAuthDate0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTelegramLoginRequestAuthDate1 returns the union data inside the TelegramLoginRequest_AuthDate as a TelegramLoginRequestAuthDate1
func (t TelegramLoginRequest_AuthDate) AsTelegramLoginRequestAuthDate1() (TelegramLoginRequestAuthDate1, error) {
	var body TelegramLoginRequestAuthDate1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramLoginRequestAuthDate1 overwrites any union data inside the TelegramLoginRequest_AuthDate as the provided TelegramLoginRequestAuthDate1
func (t *TelegramLoginRequest_AuthDate) FromTelegramLoginRequestAuthDate1(v TelegramLoginRequestAuthDate1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTelegramLoginRequestAuthDate1 performs a merge with any union data inside the TelegramLoginRequest_AuthDate, using the provided TelegramLoginRequestAuthDate1
func (t *TelegramLoginRequest_AuthDate) MergeTelegramLoginRequestAuthDate1(v TelegramLoginRequestAuthDate1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TelegramLoginRequest_AuthDate) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TelegramLoginRequest_AuthDate) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
