// Command natskeygen provisions per-service NATS nkey credentials and the
// server-side authorization block that scopes each service to the subjects it
// actually uses.
//
// For every OneVoice service it mints an ed25519 nkey user keypair, writes the
// secret seed to infra/nats/creds/<service>.nk (0600, gitignored — this is the
// service's credential), and emits infra/nats/creds/auth.conf: a NATS
// `authorization { users: [...] }` block mapping each service's PUBLIC key to a
// publish/subscribe allow-list. The seed never leaves the file; the client signs
// the server's nonce with it (see pkg/natsauth NATS_NKEY_SEED). Only public keys
// appear in auth.conf, so that file is safe to inspect but is regenerated per
// deploy (fresh keys) and therefore also gitignored.
//
// The permission sets below are derived from the verified NATS pub/sub map: the
// orchestrator and api originate requests (publish tasks.*, read their reply
// inboxes); each agent only subscribes to its own tasks.<platform> subject and
// its own revoke feed, and replies via allow_responses (permitted to answer only
// the inbox of a request it actually received — no blanket _INBOX.> publish).
//
// Idempotent: a second run that finds auth.conf is a no-op unless -force is set.
// Invoked by `make nats-creds`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nats-io/nkeys"

	"github.com/f1xgun/onevoice/pkg/natsauth"
)

// File modes for the generated material.
const (
	credsDirMode os.FileMode = 0o750 // dir holding seeds + auth.conf
	seedFileMode os.FileMode = 0o600 // per-service nkey seed — secret
	authConfMode os.FileMode = 0o644 // public keys only; the nats container (which may run non-root) must read it
)

// svcPerm is one service's NATS identity-to-be plus the subjects it may use.
type svcPerm struct {
	service        string
	publishAllow   []string
	subscribeAllow []string
	allowResponses bool // may publish a reply to the inbox of a received request
}

// perms is the authoritative per-service NATS permission model. Keep it in sync
// with pkg/a2a/protocol.go subjects and the pub/sub map in
// docs/runbook/observability.md is NOT the source — this file is.
var perms = []svcPerm{
	{
		service:        "orchestrator",
		publishAllow:   []string{"tasks.*"},
		subscribeAllow: []string{"_INBOX.>"},
	},
	{
		service:        "api",
		publishAllow:   []string{"tasks.*", "integrations.revoked.*.*"},
		subscribeAllow: []string{"_INBOX.>", "hitl.callbacks.telegram", "hitl.owner_link.telegram"},
	},
	{
		service:        "agent-telegram",
		publishAllow:   []string{"hitl.callbacks.telegram", "hitl.owner_link.telegram"},
		subscribeAllow: []string{"tasks.telegram", "integrations.revoked.telegram.*"},
		allowResponses: true,
	},
	{
		service:        "agent-vk",
		subscribeAllow: []string{"tasks.vk", "integrations.revoked.vk.*"},
		allowResponses: true,
	},
	{
		service:        "agent-yandex-business",
		subscribeAllow: []string{"tasks.yandex_business", "integrations.revoked.yandex_business.*"},
		allowResponses: true,
	},
	{
		service:        "agent-google-business",
		subscribeAllow: []string{"tasks.google_business", "integrations.revoked.google_business.*"},
		allowResponses: true,
	},
}

func main() {
	out := flag.String("out", "infra/nats/creds", "output directory for seeds and auth.conf")
	force := flag.Bool("force", false, "regenerate even if auth.conf already exists")
	refresh := flag.Bool("refresh", false, "refresh authorization from existing seeds without rotating identities")
	flag.Parse()
	if *force && *refresh {
		fail("-force and -refresh cannot be combined")
	}

	authPath := filepath.Join(*out, "auth.conf")
	if !*force && !*refresh {
		if _, err := os.Stat(authPath); err == nil {
			fmt.Printf("✓ %s already exists — skipping (run with -force, or `make clean-nats-creds`)\n", authPath)
			return
		}
	}

	if err := os.MkdirAll(*out, credsDirMode); err != nil {
		fail("create output dir: %v", err)
	}

	var users []string
	for _, p := range perms {
		seedPath := filepath.Join(*out, p.service+".nk")
		kp, err := serviceKey(seedPath, *refresh)
		if err != nil {
			fail("create nkey for %s: %v", p.service, err)
		}
		seed, err := kp.Seed()
		if err != nil {
			fail("read seed for %s: %v", p.service, err)
		}
		pub, err := kp.PublicKey()
		if err != nil {
			fail("read public key for %s: %v", p.service, err)
		}

		if !*refresh {
			if err := os.WriteFile(seedPath, append(seed, '\n'), seedFileMode); err != nil {
				fail("write seed %s: %v", seedPath, err)
			}
		}
		kp.Wipe()

		users = append(users, renderUser(p, pub))
		fmt.Printf("  • %-22s → %s\n", p.service, seedPath)
	}

	conf := "# GENERATED by tools/natskeygen — DO NOT EDIT BY HAND.\n" +
		"# Regenerate with `make nats-creds` (idempotent; `make clean-nats-creds` to force).\n" +
		"# Maps each service's nkey PUBLIC key to its subject-scoped permission set.\n" +
		"# The private seeds live beside this file as <service>.nk (gitignored); only\n" +
		"# public keys appear here. This file is regenerated per deploy and is gitignored.\n" +
		"authorization {\n" +
		"  users: [\n" +
		strings.Join(users, "") +
		"  ]\n" +
		"}\n"

	// authConfMode is 0644: auth.conf holds only public keys and must be readable
	// by the nats container (which may run as a non-root uid); seeds are 0600.
	if err := os.WriteFile(authPath, []byte(conf), authConfMode); err != nil {
		fail("write %s: %v", authPath, err)
	}
	fmt.Printf("✓ wrote %s (%d users)\n", authPath, len(perms))
}

// renderUser renders one user block in NATS config syntax.
func renderUser(p svcPerm, pub string) string {
	var b strings.Builder
	b.WriteString("    {\n")
	fmt.Fprintf(&b, "      # %s\n", p.service)
	fmt.Fprintf(&b, "      nkey: %q\n", pub)
	b.WriteString("      permissions {\n")
	if len(p.publishAllow) > 0 {
		fmt.Fprintf(&b, "        publish { allow: [%s] }\n", quoteList(p.publishAllow))
	}
	if len(p.subscribeAllow) > 0 {
		fmt.Fprintf(&b, "        subscribe { allow: [%s] }\n", quoteList(p.subscribeAllow))
	}
	if p.allowResponses {
		fmt.Fprintf(&b, "        allow_responses: { max: 1, expires: %q }\n", natsauth.ResponsePermissionTTL.String())
	}
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	return b.String()
}

// quoteList renders subjects as a quoted, comma-separated NATS config array body.
func quoteList(subjects []string) string {
	quoted := make([]string, len(subjects))
	for i, s := range subjects {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "natskeygen: "+format+"\n", args...)
	os.Exit(1)
}

func serviceKey(path string, refresh bool) (nkeys.KeyPair, error) {
	if !refresh {
		return nkeys.CreateUser()
	}
	seed, err := os.ReadFile(path) //nolint:gosec // The operator selects the seed directory via the CLI -out flag.
	if err != nil {
		return nil, fmt.Errorf("read existing seed %q: %w", path, err)
	}
	defer clear(seed)
	key, err := nkeys.FromSeed([]byte(strings.TrimSpace(string(seed))))
	if err != nil {
		return nil, fmt.Errorf("parse existing seed %q: %w", path, err)
	}
	return key, nil
}
